# This file was auto-generated by Fern from our API Definition.

import typing

UpdateAgentRequestBackgroundNoisePreset = typing.Union[
    typing.Literal["office", "city", "forest", "crowded_room", "keyboard_typing", "hold_music", ""], typing.Any
]
