# This file was auto-generated by Fern from our API Definition.

import typing

UpdateAgentRequestSttOverride = typing.Union[
    typing.Literal["flux", "whisper-v3", "gpt-realtime-whisper", ""], typing.Any
]
