# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .types import (
        CreateVoiceLanguage,
        CreateVoiceModel,
        CreateVoiceModelName,
        CreatedVoice,
        CreatedVoiceGender,
        CreatedVoiceType,
        Error,
        ErrorCode,
        ErrorDetail,
        GetSpeechOptionsRequest,
        GetSpeechResponse,
        GetSpeechResponseAudioFormat,
        GetStreamOptionsRequest,
        GetVoice,
        GetVoiceGender,
        GetVoiceLanguage,
        GetVoiceType,
        GetVoicesModel,
        GetVoicesModelName,
        NestedChunk,
        SpeechMarks,
    )
    from .errors import (
        BadGatewayError,
        BadRequestError,
        ForbiddenError,
        InternalServerError,
        NotFoundError,
        PaymentRequiredError,
        ServiceUnavailableError,
        TooManyRequestsError,
        UnauthorizedError,
        UnprocessableEntityError,
    )
    from . import tts
    from ._default_clients import DefaultAioHttpClient, DefaultAsyncHttpxClient
    from .client import AsyncSpeechify, Speechify
    from .environment import SpeechifyEnvironment
    from .version import __version__
_dynamic_imports: typing.Dict[str, str] = {
    "AsyncSpeechify": ".client",
    "BadGatewayError": ".errors",
    "BadRequestError": ".errors",
    "CreateVoiceLanguage": ".types",
    "CreateVoiceModel": ".types",
    "CreateVoiceModelName": ".types",
    "CreatedVoice": ".types",
    "CreatedVoiceGender": ".types",
    "CreatedVoiceType": ".types",
    "DefaultAioHttpClient": "._default_clients",
    "DefaultAsyncHttpxClient": "._default_clients",
    "Error": ".types",
    "ErrorCode": ".types",
    "ErrorDetail": ".types",
    "ForbiddenError": ".errors",
    "GetSpeechOptionsRequest": ".types",
    "GetSpeechResponse": ".types",
    "GetSpeechResponseAudioFormat": ".types",
    "GetStreamOptionsRequest": ".types",
    "GetVoice": ".types",
    "GetVoiceGender": ".types",
    "GetVoiceLanguage": ".types",
    "GetVoiceType": ".types",
    "GetVoicesModel": ".types",
    "GetVoicesModelName": ".types",
    "InternalServerError": ".errors",
    "NestedChunk": ".types",
    "NotFoundError": ".errors",
    "PaymentRequiredError": ".errors",
    "ServiceUnavailableError": ".errors",
    "SpeechMarks": ".types",
    "Speechify": ".client",
    "SpeechifyEnvironment": ".environment",
    "TooManyRequestsError": ".errors",
    "UnauthorizedError": ".errors",
    "UnprocessableEntityError": ".errors",
    "__version__": ".version",
    "tts": ".tts",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "AsyncSpeechify",
    "BadGatewayError",
    "BadRequestError",
    "CreateVoiceLanguage",
    "CreateVoiceModel",
    "CreateVoiceModelName",
    "CreatedVoice",
    "CreatedVoiceGender",
    "CreatedVoiceType",
    "DefaultAioHttpClient",
    "DefaultAsyncHttpxClient",
    "Error",
    "ErrorCode",
    "ErrorDetail",
    "ForbiddenError",
    "GetSpeechOptionsRequest",
    "GetSpeechResponse",
    "GetSpeechResponseAudioFormat",
    "GetStreamOptionsRequest",
    "GetVoice",
    "GetVoiceGender",
    "GetVoiceLanguage",
    "GetVoiceType",
    "GetVoicesModel",
    "GetVoicesModelName",
    "InternalServerError",
    "NestedChunk",
    "NotFoundError",
    "PaymentRequiredError",
    "ServiceUnavailableError",
    "SpeechMarks",
    "Speechify",
    "SpeechifyEnvironment",
    "TooManyRequestsError",
    "UnauthorizedError",
    "UnprocessableEntityError",
    "__version__",
    "tts",
]
