# This file was auto-generated by Fern from our API Definition.

import typing
from ...types.system_tool_config import SystemToolConfig
from ...types.webhook_tool_config import WebhookToolConfig
from ...types.client_tool_config import ClientToolConfig

CreateToolRequestConfig = typing.Union[SystemToolConfig, WebhookToolConfig, ClientToolConfig]
