# This file was auto-generated by Fern from our API Definition.

import typing
from ....types.reply_config import ReplyConfig
from ....types.tool_call_config import ToolCallConfig
from ....types.simulation_config import SimulationConfig

UpdateAgentTestRequestConfig = typing.Union[ReplyConfig, ToolCallConfig, SimulationConfig]
