# This file was auto-generated by Fern from our API Definition.

import typing

from .. import core
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.created_voice import CreatedVoice
from ..types.get_voice import GetVoice
from .raw_client import AsyncRawVoicesClient, RawVoicesClient
from .types.create_voices_request_gender import CreateVoicesRequestGender

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class VoicesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawVoicesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawVoicesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawVoicesClient
        """
        return self._raw_client

    def list(self, *, request_options: typing.Optional[RequestOptions] = None) -> typing.List[GetVoice]:
        """
        Gets the list of voices available for the user

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[GetVoice]
            A list of voices

        Examples
        --------
        from speechify import Speechify

        client = Speechify(
            api_key="YOUR_API_KEY",
        )
        client.voices.list()
        """
        _response = self._raw_client.list(request_options=request_options)
        return _response.data

    def create(
        self,
        *,
        name: str,
        gender: CreateVoicesRequestGender,
        sample: core.File,
        consent: str,
        locale: typing.Optional[str] = OMIT,
        avatar: typing.Optional[core.File] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreatedVoice:
        """
        Create a personal (cloned) voice for the user

        Parameters
        ----------
        name : str
            Name of the personal voice

        gender : CreateVoicesRequestGender
            Gender marker for the personal voice
            male GenderMale
            female GenderFemale
            notSpecified GenderNotSpecified

        sample : core.File
            See core.File for more documentation

        consent : str
            A **string** representing the user consent information in JSON format
            This should include the fullName and email of the consenting individual.
            For example, `{"fullName": "John Doe", "email": "john@example.com"}`

        locale : typing.Optional[str]
            Native language (locale) of the personal voice (e.g. en-US, es-ES, etc.)

        avatar : typing.Optional[core.File]
            See core.File for more documentation

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreatedVoice
            A created voice

        Examples
        --------
        from speechify import Speechify

        client = Speechify(
            api_key="YOUR_API_KEY",
        )
        client.voices.create(
            name="name",
            gender="male",
            consent="consent",
        )
        """
        _response = self._raw_client.create(
            name=name,
            gender=gender,
            sample=sample,
            consent=consent,
            locale=locale,
            avatar=avatar,
            request_options=request_options,
        )
        return _response.data

    def delete(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Delete a personal (cloned) voice

        Parameters
        ----------
        id : str
            The ID of the voice to delete

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from speechify import Speechify

        client = Speechify(
            api_key="YOUR_API_KEY",
        )
        client.voices.delete(
            id="id",
        )
        """
        _response = self._raw_client.delete(id, request_options=request_options)
        return _response.data

    def download_sample(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Iterator[bytes]:
        """
        Download a personal (cloned) voice sample

        Parameters
        ----------
        id : str
            The ID of the voice to download sample for

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration. You can pass in configuration such as `chunk_size`, and more to customize the request and response.

        Returns
        -------
        typing.Iterator[bytes]
            Voice sample audio file

        Examples
        --------
        from speechify import Speechify

        client = Speechify(
            api_key="YOUR_API_KEY",
        )
        client.voices.download_sample(
            id="id",
        )
        """
        with self._raw_client.download_sample(id, request_options=request_options) as r:
            yield from r.data


class AsyncVoicesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawVoicesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawVoicesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawVoicesClient
        """
        return self._raw_client

    async def list(self, *, request_options: typing.Optional[RequestOptions] = None) -> typing.List[GetVoice]:
        """
        Gets the list of voices available for the user

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[GetVoice]
            A list of voices

        Examples
        --------
        import asyncio

        from speechify import AsyncSpeechify

        client = AsyncSpeechify(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.voices.list()


        asyncio.run(main())
        """
        _response = await self._raw_client.list(request_options=request_options)
        return _response.data

    async def create(
        self,
        *,
        name: str,
        gender: CreateVoicesRequestGender,
        sample: core.File,
        consent: str,
        locale: typing.Optional[str] = OMIT,
        avatar: typing.Optional[core.File] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreatedVoice:
        """
        Create a personal (cloned) voice for the user

        Parameters
        ----------
        name : str
            Name of the personal voice

        gender : CreateVoicesRequestGender
            Gender marker for the personal voice
            male GenderMale
            female GenderFemale
            notSpecified GenderNotSpecified

        sample : core.File
            See core.File for more documentation

        consent : str
            A **string** representing the user consent information in JSON format
            This should include the fullName and email of the consenting individual.
            For example, `{"fullName": "John Doe", "email": "john@example.com"}`

        locale : typing.Optional[str]
            Native language (locale) of the personal voice (e.g. en-US, es-ES, etc.)

        avatar : typing.Optional[core.File]
            See core.File for more documentation

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreatedVoice
            A created voice

        Examples
        --------
        import asyncio

        from speechify import AsyncSpeechify

        client = AsyncSpeechify(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.voices.create(
                name="name",
                gender="male",
                consent="consent",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create(
            name=name,
            gender=gender,
            sample=sample,
            consent=consent,
            locale=locale,
            avatar=avatar,
            request_options=request_options,
        )
        return _response.data

    async def delete(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Delete a personal (cloned) voice

        Parameters
        ----------
        id : str
            The ID of the voice to delete

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from speechify import AsyncSpeechify

        client = AsyncSpeechify(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.voices.delete(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete(id, request_options=request_options)
        return _response.data

    async def download_sample(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.AsyncIterator[bytes]:
        """
        Download a personal (cloned) voice sample

        Parameters
        ----------
        id : str
            The ID of the voice to download sample for

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration. You can pass in configuration such as `chunk_size`, and more to customize the request and response.

        Returns
        -------
        typing.AsyncIterator[bytes]
            Voice sample audio file

        Examples
        --------
        import asyncio

        from speechify import AsyncSpeechify

        client = AsyncSpeechify(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.voices.download_sample(
                id="id",
            )


        asyncio.run(main())
        """
        async with self._raw_client.download_sample(id, request_options=request_options) as r:
            async for _chunk in r.data:
                yield _chunk
