# This file was auto-generated by Fern from our API Definition.

import typing
from ...core.client_wrapper import SyncClientWrapper
from ...types.amd_config import AmdConfig
from ...core.request_options import RequestOptions
from ...types.create_outbound_call_response import CreateOutboundCallResponse
from ...core.serialization import convert_and_respect_annotation_metadata
from ...core.pydantic_utilities import parse_obj_as
from ...errors.bad_request_error import BadRequestError
from ...errors.unauthorized_error import UnauthorizedError
from ...errors.not_found_error import NotFoundError
from json.decoder import JSONDecodeError
from ...core.api_error import ApiError
from ...core.client_wrapper import AsyncClientWrapper

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class OutboundCallsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def create(
        self,
        *,
        agent_id: str,
        to: str,
        caller_id_number: typing.Optional[str] = OMIT,
        dtmf_prefix: typing.Optional[str] = OMIT,
        dynamic_variables: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = OMIT,
        ringing_timeout_ms: typing.Optional[int] = OMIT,
        amd: typing.Optional[AmdConfig] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreateOutboundCallResponse:
        """
        Place an outbound call from an agent to a phone number. LiveKit
        originates the SIP INVITE through the outbound trunk bound to the
        agent's workspace; the agent worker is dispatched into the room
        automatically.

        The response is returned as soon as LiveKit accepts the INVITE.
        Poll `GET /v1/agents/conversations/{conversation_id}` for status
        transitions: `pending` → `active` (answered) → `completed`.

        Requires a Twilio or BYOC trunk. LiveKit-native numbers are
        inbound-only.

        Parameters
        ----------
        agent_id : str
            ID of the agent that handles the answered call.

        to : str
            Destination phone number in E.164 format (e.g. `+12025559876`).

        caller_id_number : typing.Optional[str]
            The number shown to the callee as caller ID, in E.164 format.
            Defaults to the first outbound-capable number in the workspace.
            Useful for multi-number campaigns where you want to rotate
            caller IDs.

        dtmf_prefix : typing.Optional[str]
            DTMF digits dialed automatically after the call is answered,
            before the agent begins speaking. Use this for IVR navigation
            (e.g. `1ww2` presses 1, waits two seconds, presses 2). `w`
            is a half-second pause; `W` is a one-second pause.

        dynamic_variables : typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]]
            Per-call variable overrides merged on top of the agent's stored
            defaults. Keys must not use the reserved `system__` prefix.
            Useful for injecting per-call context (customer name, order ID)
            into the agent prompt.

        ringing_timeout_ms : typing.Optional[int]
            How long to wait for the callee to answer before abandoning,
            in milliseconds. Defaults to 30000 (30s). Capped at 80000 (80s).

        amd : typing.Optional[AmdConfig]
            Optional per-call override for the AMD routing config. When
            set, wholesale-replaces the agent's stored AMD shape for
            this single call (PATCH-replace, not merge). Unlocks the
            batch-campaign pattern: one agent dialling many recipients
            with per-row tailored voicemail messages via the existing
            dynamic_variables substitution. Validation rules match
            the agent-update boundary.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateOutboundCallResponse
            The outbound call was accepted by LiveKit.

        Examples
        --------
        from speechify import Speechify

        client = Speechify(
            token="YOUR_TOKEN",
        )
        client.agent.outbound_calls.create(
            agent_id="agent_01HS...",
            to="+41791234567",
            caller_id_number="+12025551234",
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/agents/outbound-calls",
            method="POST",
            json={
                "agent_id": agent_id,
                "to": to,
                "caller_id_number": caller_id_number,
                "dtmf_prefix": dtmf_prefix,
                "dynamic_variables": dynamic_variables,
                "ringing_timeout_ms": ringing_timeout_ms,
                "amd": convert_and_respect_annotation_metadata(object_=amd, annotation=AmdConfig, direction="write"),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    CreateOutboundCallResponse,
                    parse_obj_as(
                        type_=CreateOutboundCallResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 400:
                raise BadRequestError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)


class AsyncOutboundCallsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def create(
        self,
        *,
        agent_id: str,
        to: str,
        caller_id_number: typing.Optional[str] = OMIT,
        dtmf_prefix: typing.Optional[str] = OMIT,
        dynamic_variables: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = OMIT,
        ringing_timeout_ms: typing.Optional[int] = OMIT,
        amd: typing.Optional[AmdConfig] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreateOutboundCallResponse:
        """
        Place an outbound call from an agent to a phone number. LiveKit
        originates the SIP INVITE through the outbound trunk bound to the
        agent's workspace; the agent worker is dispatched into the room
        automatically.

        The response is returned as soon as LiveKit accepts the INVITE.
        Poll `GET /v1/agents/conversations/{conversation_id}` for status
        transitions: `pending` → `active` (answered) → `completed`.

        Requires a Twilio or BYOC trunk. LiveKit-native numbers are
        inbound-only.

        Parameters
        ----------
        agent_id : str
            ID of the agent that handles the answered call.

        to : str
            Destination phone number in E.164 format (e.g. `+12025559876`).

        caller_id_number : typing.Optional[str]
            The number shown to the callee as caller ID, in E.164 format.
            Defaults to the first outbound-capable number in the workspace.
            Useful for multi-number campaigns where you want to rotate
            caller IDs.

        dtmf_prefix : typing.Optional[str]
            DTMF digits dialed automatically after the call is answered,
            before the agent begins speaking. Use this for IVR navigation
            (e.g. `1ww2` presses 1, waits two seconds, presses 2). `w`
            is a half-second pause; `W` is a one-second pause.

        dynamic_variables : typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]]
            Per-call variable overrides merged on top of the agent's stored
            defaults. Keys must not use the reserved `system__` prefix.
            Useful for injecting per-call context (customer name, order ID)
            into the agent prompt.

        ringing_timeout_ms : typing.Optional[int]
            How long to wait for the callee to answer before abandoning,
            in milliseconds. Defaults to 30000 (30s). Capped at 80000 (80s).

        amd : typing.Optional[AmdConfig]
            Optional per-call override for the AMD routing config. When
            set, wholesale-replaces the agent's stored AMD shape for
            this single call (PATCH-replace, not merge). Unlocks the
            batch-campaign pattern: one agent dialling many recipients
            with per-row tailored voicemail messages via the existing
            dynamic_variables substitution. Validation rules match
            the agent-update boundary.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateOutboundCallResponse
            The outbound call was accepted by LiveKit.

        Examples
        --------
        import asyncio

        from speechify import AsyncSpeechify

        client = AsyncSpeechify(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.agent.outbound_calls.create(
                agent_id="agent_01HS...",
                to="+41791234567",
                caller_id_number="+12025551234",
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/agents/outbound-calls",
            method="POST",
            json={
                "agent_id": agent_id,
                "to": to,
                "caller_id_number": caller_id_number,
                "dtmf_prefix": dtmf_prefix,
                "dynamic_variables": dynamic_variables,
                "ringing_timeout_ms": ringing_timeout_ms,
                "amd": convert_and_respect_annotation_metadata(object_=amd, annotation=AmdConfig, direction="write"),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    CreateOutboundCallResponse,
                    parse_obj_as(
                        type_=CreateOutboundCallResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 400:
                raise BadRequestError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)
