# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .create_voice_language import CreateVoiceLanguage
    from .create_voice_model import CreateVoiceModel
    from .create_voice_model_name import CreateVoiceModelName
    from .created_voice import CreatedVoice
    from .created_voice_gender import CreatedVoiceGender
    from .created_voice_type import CreatedVoiceType
    from .error import Error
    from .error_code import ErrorCode
    from .error_detail import ErrorDetail
    from .get_speech_options_request import GetSpeechOptionsRequest
    from .get_speech_response import GetSpeechResponse
    from .get_speech_response_audio_format import GetSpeechResponseAudioFormat
    from .get_stream_options_request import GetStreamOptionsRequest
    from .get_voice import GetVoice
    from .get_voice_gender import GetVoiceGender
    from .get_voice_language import GetVoiceLanguage
    from .get_voice_type import GetVoiceType
    from .get_voices_model import GetVoicesModel
    from .get_voices_model_name import GetVoicesModelName
    from .nested_chunk import NestedChunk
    from .speech_marks import SpeechMarks
_dynamic_imports: typing.Dict[str, str] = {
    "CreateVoiceLanguage": ".create_voice_language",
    "CreateVoiceModel": ".create_voice_model",
    "CreateVoiceModelName": ".create_voice_model_name",
    "CreatedVoice": ".created_voice",
    "CreatedVoiceGender": ".created_voice_gender",
    "CreatedVoiceType": ".created_voice_type",
    "Error": ".error",
    "ErrorCode": ".error_code",
    "ErrorDetail": ".error_detail",
    "GetSpeechOptionsRequest": ".get_speech_options_request",
    "GetSpeechResponse": ".get_speech_response",
    "GetSpeechResponseAudioFormat": ".get_speech_response_audio_format",
    "GetStreamOptionsRequest": ".get_stream_options_request",
    "GetVoice": ".get_voice",
    "GetVoiceGender": ".get_voice_gender",
    "GetVoiceLanguage": ".get_voice_language",
    "GetVoiceType": ".get_voice_type",
    "GetVoicesModel": ".get_voices_model",
    "GetVoicesModelName": ".get_voices_model_name",
    "NestedChunk": ".nested_chunk",
    "SpeechMarks": ".speech_marks",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "CreateVoiceLanguage",
    "CreateVoiceModel",
    "CreateVoiceModelName",
    "CreatedVoice",
    "CreatedVoiceGender",
    "CreatedVoiceType",
    "Error",
    "ErrorCode",
    "ErrorDetail",
    "GetSpeechOptionsRequest",
    "GetSpeechResponse",
    "GetSpeechResponseAudioFormat",
    "GetStreamOptionsRequest",
    "GetVoice",
    "GetVoiceGender",
    "GetVoiceLanguage",
    "GetVoiceType",
    "GetVoicesModel",
    "GetVoicesModelName",
    "NestedChunk",
    "SpeechMarks",
]
