# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import pydantic
import typing
import datetime as dt
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class AgentTestFolder(UniversalBaseModel):
    """
    One organisational node in the per-owner tests tree.
    """

    id: str = pydantic.Field()
    """
    Prefixed wire identifier (`folder_<26 char Crockford base32>`).
    URL paths accept only this
    prefixed form; legacy UUID path parameters are rejected with
    404.
    """

    parent_folder_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    When set, prefixed wire identifier
    (`folder_<26 char Crockford base32>`) of the parent folder.
    Null means root.
    """

    name: str
    created_at: dt.datetime
    updated_at: dt.datetime

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
