# This file was auto-generated by Fern from our API Definition.

import typing
from .reply_config import ReplyConfig
from .tool_call_config import ToolCallConfig
from .simulation_config import SimulationConfig

AgentTestConfig = typing.Union[ReplyConfig, ToolCallConfig, SimulationConfig]
