# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import pydantic
from .system_builtin import SystemBuiltin
import typing
import datetime as dt
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class AgentBuiltin(UniversalBaseModel):
    """
    One instance of a system builtin bound to a specific agent.
    Storage lives in the `agent_builtins` table (migration 00061);
    wire format intentionally matches the legacy `kind="system"`
    Tool shape so the worker is untouched by the split.
    """

    id: str = pydantic.Field()
    """
    Opaque builtin instance ID.
    """

    tenant_id: str = pydantic.Field()
    """
    The workspace owning this instance.
    """

    agent_id: str = pydantic.Field()
    """
    The agent this instance is bound to.
    """

    builtin: SystemBuiltin
    name: str = pydantic.Field()
    """
    LLM-facing tool name. Unique within the agent's builtin set.
    """

    description: str = pydantic.Field()
    """
    LLM-facing one-line description of when to call the tool.
    """

    config: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = pydantic.Field(default=None)
    """
    Per-instance configuration shape. The schema depends on
    `builtin` — see the per-builtin contracts under
    `/contracts/tools/system_*.schema.json`. Null when the
    builtin takes no instance-level config.
    """

    params: typing.Optional[typing.List[typing.Dict[str, typing.Optional[typing.Any]]]] = pydantic.Field(default=None)
    """
    Per-call parameter schema fragment merged into the model's
    tool spec. Each entry is one parameter descriptor (the
    per-builtin contract pins the exact shape). Null when the
    builtin takes no caller arguments.
    """

    enabled: bool = pydantic.Field()
    """
    When false, the instance is persisted but skipped at dispatch.
    """

    created_at: dt.datetime
    updated_at: dt.datetime

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
