# This file was auto-generated by Fern from our API Definition.

from .agent_test_suite_run import AgentTestSuiteRun
import typing
from .suite_child_run import SuiteChildRun
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class AgentTestSuiteRunWithRuns(AgentTestSuiteRun):
    """
    A suite run plus every child run, for the grouped detail view.
    """

    runs: typing.List[SuiteChildRun]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
