# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import pydantic
import typing
from .suite_run_trigger import SuiteRunTrigger
from .test_run_status import TestRunStatus
import datetime as dt
from .test_run_config_override import TestRunConfigOverride
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class AgentTestSuiteRun(UniversalBaseModel):
    """
    A suite run (test invocation): the grouping object over every
    test run dispatched by one Run All, batch, or resubmit call.
    `status` and the count fields are derived from the child runs.
    `status` is `running` while any child run is still queued or
    running, then `passed` (all passed), `failed` (at least one
    failed), or `error` (at least one errored, none failed).
    """

    id: str = pydantic.Field()
    """
    Prefixed wire identifier (`srun_<26 char Crockford base32>`).
    """

    agent_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Prefixed `agent_<crockford>` id of the agent whose suite
    was run. Set for the `run_all` trigger; null for `batch`,
    which can span many agents.
    """

    agent_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Display name of `agent_id`'s agent, resolved at read time.
    Null whenever `agent_id` is null, and on the suite run
    embedded in run/resubmit creation responses.
    """

    trigger: SuiteRunTrigger
    parent_suite_run_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Set on a `resubmit`: the prefixed `srun_<crockford>` id of
    the suite run whose failed/errored tests this one re-ran.
    Null for `run_all` and `batch`.
    """

    status: TestRunStatus
    total_runs: int = pydantic.Field()
    """
    Number of child runs in the suite.
    """

    passed_count: int
    failed_count: int
    errored_count: int
    pending_count: int = pydantic.Field()
    """
    Child runs still queued or running.
    """

    created_at: dt.datetime
    completed_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    Newest child-run completion; null until every child run is terminal.
    """

    config_override: typing.Optional[TestRunConfigOverride] = pydantic.Field(default=None)
    """
    The run-level config override this suite was run
    with, or null for an ordinary Run All / batch.
    """

    flow_version_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The flow version (`agent_versions` row) this suite targeted,
    or null for the agent's active / synthesized flow.
    """

    flow_version_number: typing.Optional[int] = pydantic.Field(default=None)
    """
    Human-facing version number of `flow_version_id`; null when no version was targeted.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
