# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
from .amd_config_on_voicemail_action import AmdConfigOnVoicemailAction
import typing
import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class AmdConfigOnVoicemail(UniversalBaseModel):
    """
    Action when AMD returns category=machine-vm.
    """

    action: AmdConfigOnVoicemailAction
    message: typing.Optional[str] = pydantic.Field(default=None)
    """
    Spoken before terminating when action=leave_message.
    Supports {{variable}} substitution. Required (non-empty)
    when action=leave_message; rejected by the validator
    otherwise.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
