# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class AmdConfigTuning(UniversalBaseModel):
    """
    Optional overrides for LiveKit's detection thresholds and
    timeouts. Cross-field rule (enforced at the application
    validator): `timeout_seconds` must be greater than or equal
    to `no_speech_threshold_seconds` when both are set.
    """

    human_speech_threshold_seconds: typing.Optional[float] = None
    no_speech_threshold_seconds: typing.Optional[float] = None
    timeout_seconds: typing.Optional[float] = None
    classification_prompt: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
