# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
from .amd_config_on_ivr_action import AmdConfigOnIvrAction
import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import typing


class AmdConfigOnIvr(UniversalBaseModel):
    """
    Action when AMD returns category=machine-ivr.
    """

    action: AmdConfigOnIvrAction = pydantic.Field()
    """
    proceed: hand control to the agent's flow as if the
    called party were human. hangup: terminate immediately.
    navigate: hand control to the IVR Navigator subagent
    with menu-memoization-aware session config (cache hit
    seeds the agent context; cache miss triggers cold
    discovery and the post-call pipeline extracts the
    menu for future calls).
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
