# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import pydantic
from .amd_config_on_voicemail import AmdConfigOnVoicemail
from .amd_config_on_ivr import AmdConfigOnIvr
from .amd_config_on_unavailable import AmdConfigOnUnavailable
import typing
from .amd_config_tuning import AmdConfigTuning
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class AmdConfig(UniversalBaseModel):
    """
    Answering Machine Detection routing config for outbound voice
    agents. AMD classifies the called party's first ~3-15 seconds of
    audio into one of LiveKit's categories (human, uncertain,
    machine-vm, machine-ivr, machine-unavailable) and dispatches per
    category to the configured action. Stored on the agent row;
    flowed onto outbound dispatch metadata under the `amd` key.
    """

    enabled: bool = pydantic.Field()
    """
    When false, the worker skips AMD entirely. When true, the
    worker runs AMD on the called party's greeting before
    delivering the agent's first message and dispatches per
    result.category. The per-route fields below are still
    required by the schema regardless of `enabled` state so a
    customer flipping `enabled: false → true` ships coherent
    route configuration immediately.
    """

    on_voicemail: AmdConfigOnVoicemail = pydantic.Field()
    """
    Action when AMD returns category=machine-vm.
    """

    on_ivr: AmdConfigOnIvr = pydantic.Field()
    """
    Action when AMD returns category=machine-ivr.
    """

    on_unavailable: AmdConfigOnUnavailable = pydantic.Field()
    """
    Action when AMD returns category=machine-unavailable (mailbox full or disconnected).
    """

    tuning: typing.Optional[AmdConfigTuning] = pydantic.Field(default=None)
    """
    Optional overrides for LiveKit's detection thresholds and
    timeouts. Cross-field rule (enforced at the application
    validator): `timeout_seconds` must be greater than or equal
    to `no_speech_threshold_seconds` when both are set.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
