# This file was auto-generated by Fern from our API Definition.

import typing

AudioStreamOutputFormat = typing.Union[
    typing.Literal[
        "pcm_8000",
        "pcm_16000",
        "pcm_22050",
        "pcm_24000",
        "pcm_44100",
        "pcm_48000",
        "mp3_22050_32",
        "mp3_22050_64",
        "mp3_22050_96",
        "mp3_22050_128",
        "mp3_22050_192",
        "mp3_24000_32",
        "mp3_24000_64",
        "mp3_24000_96",
        "mp3_24000_128",
        "mp3_24000_192",
        "ulaw_8000",
        "ogg_24000",
        "aac_24000",
    ],
    typing.Any,
]
