# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import pydantic
import datetime as dt
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import typing


class AudioAsset(UniversalBaseModel):
    """
    Metadata for a pre-recorded WAV clip stored in the workspace's
    audio-asset bucket. Bytes are immutable once uploaded — to
    replace a clip, upload a new asset and update any references.
    """

    id: str = pydantic.Field()
    """
    Prefixed wire identifier (`audio_<26 char Crockford base32>`).
    URL paths accept only this
    prefixed form; legacy UUID path parameters are rejected with
    404.
    """

    original_filename: str = pydantic.Field()
    """
    The filename supplied at upload time, kept for display.
    """

    content_type: str = pydantic.Field()
    """
    Always `audio/wav`. Pinned server-side after WAV validation
    rather than trusting the upload's multipart Content-Type
    header.
    """

    size_bytes: int = pydantic.Field()
    """
    Stored byte length. Capped at 4 MiB at upload time.
    """

    duration_ms: int = pydantic.Field()
    """
    Clip duration in milliseconds. Capped at 30000 (30s) at upload time.
    """

    sample_rate_hz: int = pydantic.Field()
    """
    WAV sample rate. Always 48000 (matches the LiveKit room rate).
    """

    channels: int = pydantic.Field()
    """
    Channel count. Always 1 (mono).
    """

    bit_depth: int = pydantic.Field()
    """
    PCM sample bit depth. Always 16.
    """

    created_at: dt.datetime

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
