# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import pydantic
import typing
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class BatchRecipientRequest(UniversalBaseModel):
    """
    One entry in a batch-call request.
    """

    phone: str = pydantic.Field()
    """
    Recipient phone number in E.164 format.
    """

    dynamic_vars: typing.Optional[typing.Dict[str, str]] = pydantic.Field(default=None)
    """
    Per-recipient variable overrides injected into the agent prompt.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
