# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import pydantic
import typing
from .batch_call_status import BatchCallStatus
import datetime as dt
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class BatchCall(UniversalBaseModel):
    """
    A batch of outbound calls dispatched to a list of recipients.
    """

    id: str = pydantic.Field()
    """
    Prefixed wire identifier (`batch_<26 char Crockford base32>`).
    URL paths accept only this
    prefixed form; legacy UUID path parameters are rejected with
    404.
    """

    agent_id: str = pydantic.Field()
    """
    Prefixed wire identifier (`agent_<26 char Crockford base32>`)
    of the agent that will run the batch.
    """

    phone_number_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Caller-ID override. When set, prefixed wire identifier
    (`phone_<26 char Crockford base32>`) of the phone number to
    use; falls back to the agent's bound number when null. ADR
    0015 FK consistency.
    """

    name: str = pydantic.Field()
    """
    Human-readable batch name.
    """

    status: BatchCallStatus
    total: int = pydantic.Field()
    """
    Total number of recipients.
    """

    completed: int = pydantic.Field()
    """
    Recipients successfully dialed.
    """

    failed: int = pydantic.Field()
    """
    Recipients that failed.
    """

    error: typing.Optional[str] = pydantic.Field(default=None)
    """
    Populated when the batch itself fails.
    """

    created_at: dt.datetime
    updated_at: dt.datetime
    started_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    When the dispatcher started dialing.
    """

    finished_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    When the last recipient was resolved.
    """

    scheduled_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    If set, the batch waits until this time before dialing.
    """

    ringing_timeout_ms: typing.Optional[int] = pydantic.Field(default=None)
    """
    Per-call ringing timeout in milliseconds applied to every
    recipient in the batch. Null when the batch uses the 30s
    default.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
