# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import pydantic
import typing
from .batch_recipient_status import BatchRecipientStatus
import datetime as dt
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class BatchRecipient(UniversalBaseModel):
    """
    One recipient row in a batch call.
    """

    id: str
    batch_id: str = pydantic.Field()
    """
    Prefixed wire identifier (`batch_<26 char Crockford base32>`)
    of the parent batch.
    """

    phone: str = pydantic.Field()
    """
    Recipient phone number in E.164 format.
    """

    dynamic_vars: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = pydantic.Field(default=None)
    """
    Per-recipient variable overrides injected into the agent prompt.
    """

    status: BatchRecipientStatus
    conversation_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Set once the call is placed. Prefixed wire identifier
    (`conv_<26 char Crockford base32>`).
    """

    error: typing.Optional[str] = pydantic.Field(default=None)
    """
    Populated when this recipient fails.
    """

    attempted_at: typing.Optional[dt.datetime] = None
    completed_at: typing.Optional[dt.datetime] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
