# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import pydantic
import typing
import datetime as dt
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class CallerMemoryItem(UniversalBaseModel):
    """
    Memory projection returned by the per-caller memories list. Mirrors
    the legacy `/v1/agents/{id}/memories` shape so console code can
    re-use existing renderers.
    """

    id: str
    agent_id: str = pydantic.Field()
    """
    Prefixed wire identifier (`agent_<26 char Crockford base32>`)
    of the owning agent.
    """

    caller_identity: str
    fact: str
    source_conversation_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    When set, the prefixed wire identifier
    (`conv_<26 char Crockford base32>`) of the conversation this
    memory was extracted from.
    """

    confidence: float
    created_at: dt.datetime

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
