# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class CreateWorkspaceRequest(UniversalBaseModel):
    """
    Body for POST /v1/workspaces. The `name` field is optional; omitting it falls back to "Workspace".
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Display name for the new workspace. Trimmed; must be 120 characters or fewer.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
