# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import typing


class CreateOutboundCallResponse(UniversalBaseModel):
    """
    Returned synchronously when LiveKit accepts the SIP INVITE. Poll
    `GET /v1/agents/conversations/{conversation_id}` for status transitions:
    `pending` (ringing) → `active` (answered) → `completed`.
    """

    conversation_id: str = pydantic.Field()
    """
    ID of the conversation created for this call. Use to poll status.
    """

    room: str = pydantic.Field()
    """
    LiveKit room name the answered call joins.
    """

    sip_participant_id: str = pydantic.Field()
    """
    LiveKit participant ID for the outbound SIP call leg.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
