# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
import pydantic
from .flow_graph_input import FlowGraphInput
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class CreateFlowTemplateRequest(UniversalBaseModel):
    """
    Request body for creating (POST) or replacing (PATCH) a flow
    template. PATCH replaces the whole template, it is not a
    field-by-field patch.
    """

    key: str
    name: str
    description: typing.Optional[str] = None
    category: typing.Optional[str] = pydantic.Field(default=None)
    """
    Defaults to "custom" when omitted.
    """

    graph: FlowGraphInput

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
