# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import pydantic
from .credential_kind import CredentialKind
from .credential_config import CredentialConfig
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import typing


class CreateCredentialRequest(UniversalBaseModel):
    """
    Body for `POST /v1/credentials`.
    """

    name: str = pydantic.Field()
    """
    Human-readable label, unique per workspace.
    """

    kind: CredentialKind
    config: CredentialConfig

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
