# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing_extensions
import typing
from .o_auth2client_credentials_config import OAuth2ClientCredentialsConfig
from ..core.serialization import FieldMetadata
from .o_auth2jwt_config import OAuth2JwtConfig
from .basic_auth_config import BasicAuthConfig
from .bearer_auth_config import BearerAuthConfig
from .custom_headers_config import CustomHeadersConfig
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class CredentialConfig(UniversalBaseModel):
    """
    Kind-specific credential payload. Exactly one block is
    populated — the one named by the credential's `kind`. The
    block IS the secret; it is echoed back decrypted on reads.
    """

    oauth2client_credentials: typing_extensions.Annotated[
        typing.Optional[OAuth2ClientCredentialsConfig], FieldMetadata(alias="oauth2_client_credentials")
    ] = None
    oauth2jwt: typing_extensions.Annotated[typing.Optional[OAuth2JwtConfig], FieldMetadata(alias="oauth2_jwt")] = None
    basic: typing.Optional[BasicAuthConfig] = None
    bearer: typing.Optional[BearerAuthConfig] = None
    custom_headers: typing.Optional[CustomHeadersConfig] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
