# This file was auto-generated by Fern from our API Definition.

import typing

CredentialKind = typing.Union[
    typing.Literal["oauth2_client_credentials", "oauth2_jwt", "basic", "bearer", "custom_headers"], typing.Any
]
