# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import typing


class DeleteCallerResponse(UniversalBaseModel):
    """
    Audit envelope returned by DELETE /v1/agents/callers/{id}. Surfaces
    the cascade row counts so a privacy operator has direct evidence
    of the purge without re-querying.
    """

    caller_purged: int = pydantic.Field()
    """
    1 on the first delete; 0 on idempotent re-delete.
    """

    memories_purged: int = pydantic.Field()
    """
    Number of user_memories rows cascade-soft-deleted under this caller.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
