# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
from .flow_graph import FlowGraph
from .flow_version import FlowVersion
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class GetFlowResponse(UniversalBaseModel):
    """
    Response for GET /v1/agents/{id}/flow.
    """

    draft: typing.Optional[FlowGraph] = None
    active: typing.Optional[FlowGraph] = None
    history: typing.List[FlowVersion]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
