# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .get_voice_gender import GetVoiceGender
from .get_voice_type import GetVoiceType
from .get_voices_model import GetVoicesModel


class GetVoice(UniversalBaseModel):
    avatar_image: typing.Optional[str] = None
    display_name: str
    gender: GetVoiceGender
    locale: str
    id: str
    models: typing.List[GetVoicesModel]
    preview_audio: typing.Optional[str] = None
    tags: typing.Optional[typing.List[str]] = None
    type: GetVoiceType

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
