# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import pydantic
from .member_role import MemberRole
import datetime as dt
import typing
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class Invite(UniversalBaseModel):
    """
    A pending or historical workspace invite.
    """

    id: str = pydantic.Field()
    """
    Opaque invite ID.
    """

    email: str = pydantic.Field()
    """
    Invitee email.
    """

    invited_by: str = pydantic.Field()
    """
    Firebase UID of the member who created the invite.
    """

    role: MemberRole = pydantic.Field()
    """
    Workspace role the invitee joins with when they accept.
    """

    created_at: dt.datetime
    expires_at: dt.datetime
    accepted_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    Populated once the invite has been accepted.
    """

    revoked_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    Populated once the invite has been revoked.
    """

    token: typing.Optional[str] = pydantic.Field(default=None)
    """
    Invite token. Returned ONLY on the create-invite response;
    subsequent list calls redact it. Use the token to build the
    `/join/{token}` join URL.
    """

    email_sent: bool = pydantic.Field()
    """
    True when the server delivered the invite email. The
    console uses this on the create-invite response to choose
    between an "email sent" confirmation and the copy-link
    fallback. Always present on the wire; on list responses
    it reflects the most recent send attempt.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
