# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import pydantic
import typing
import datetime as dt
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class IvrMenu(UniversalBaseModel):
    """
    One memorized IVR menu level. Identified by the
    SHA-256 fingerprint of the normalized greeting transcript;
    scoped to the caller's workspace (foreign-tenant menus are
    never returned).

    `menu_tree` is the validated JSONB blob the worker consumes:
    prompt text plus the options offered (label + DTMF). Sub-menus
    reached by pressing an option are their own rows, looked up at
    descent time by a fresh fingerprint - the tree structure is the
    implicit graph of fingerprint -> fingerprint transitions.

    `confidence_score` is `succeeded_traversals / total_traversals`.
    The worker's plan-then-execute fast path only activates at or
    above 0.5.

    `invalidated_at` is non-null on a soft-deleted row; the API
    filters these out of list / lookup / get responses so this field
    is informational only.
    """

    id: str = pydantic.Field()
    """
    Prefixed wire identifier (`menu_<26 char Crockford base32>`).
    URL paths accept only this
    prefixed form; legacy UUID path parameters are rejected with
    404.
    """

    fingerprint_id: str
    tenant_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Null on the cross-tenant promoted slot.
    """

    schema_version: int
    menu_tree: typing.Dict[str, typing.Optional[typing.Any]] = pydantic.Field()
    """
    Validated menu_tree per contracts/agents/ivr_menu.schema.json. Opaque to consumers other than the worker.
    """

    confidence_score: float
    succeeded_traversals: int
    total_traversals: int
    last_validated_at: dt.datetime
    invalidated_at: typing.Optional[dt.datetime] = None
    created_at: dt.datetime
    updated_at: dt.datetime

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
