# This file was auto-generated by Fern from our API Definition.

from .knowledge_base_document import KnowledgeBaseDocument
import typing
from .dependent_agent import DependentAgent
from .refresh_config import RefreshConfig
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class KnowledgeBaseDocumentDetail(KnowledgeBaseDocument):
    """
    Payload of GET /v1/knowledge-bases/documents/{docId}. Extends
    the list-view document with a bounded content preview, the
    list of dependent agents, and (for url-sourced docs) the
    auto-refresh state.
    """

    content_preview: str
    preview_truncated: bool
    dependent_agents: typing.List[DependentAgent]
    refresh: typing.Optional[RefreshConfig] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
