# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import typing


class KnowledgeBaseChunk(UniversalBaseModel):
    id: str
    document_id: str
    kb_id: str = pydantic.Field()
    """
    Prefixed wire identifier (`kb_<26 char Crockford base32>`) of
    the knowledge base the chunk belongs to.
    """

    chunk_index: int
    content: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
