# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
from .dynamic_variable import DynamicVariable
import pydantic
from .system_variable_doc import SystemVariableDoc
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class ListDynamicVariablesResponse(UniversalBaseModel):
    """
    Response for `GET /v1/agents/{id}/variables`. Returns both the
    customer-scope variable catalogue and the read-only `system__*`
    catalogue so the editor UI has a single source of truth.
    """

    variables: typing.List[DynamicVariable] = pydantic.Field()
    """
    Customer-defined variables for this agent.
    """

    system_variables: typing.List[SystemVariableDoc] = pydantic.Field()
    """
    Platform-populated `system__*` variables, provided for
    reference. This list is the same for every agent.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
