# This file was auto-generated by Fern from our API Definition.

from .pagination_meta import PaginationMeta
import typing
from .message import Message
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class ListMessagesResponse(PaginationMeta):
    messages: typing.List[Message]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
