# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from .get_voice import GetVoice
from .pagination_meta import PaginationMeta


class ListVoicesResponse(PaginationMeta):
    """
    Payload for `GET /v1/voices` - the shared voice catalog plus the
    workspace's personal cloned voices. Carries the shared pagination
    metadata so the list can be paged when `limit` is supplied;
    `next_cursor` is null and `has_more` is false when the full
    catalogue is returned in one response.
    """

    voices: typing.List[GetVoice]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
