# This file was auto-generated by Fern from our API Definition.

from .pagination_meta import PaginationMeta
import typing
from .recent_callee import RecentCallee
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class ListRecentCalleesResponse(PaginationMeta):
    """
    Payload for GET /v1/agents/conversations/recent-callees.
    """

    callees: typing.List[RecentCallee]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
