# This file was auto-generated by Fern from our API Definition.

import typing

McpProbeErrorDetailsStage = typing.Union[
    typing.Literal["validation", "oauth2_token", "mcp_connect", "mcp_initialize", "mcp_notify", "mcp_list_tools"],
    typing.Any,
]
