# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
from .mcp_probe_error_details_stage import McpProbeErrorDetailsStage
import typing_extensions
from ..core.serialization import FieldMetadata
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class McpProbeErrorDetails(UniversalBaseModel):
    """
    Structured upstream signal for an MCP probe failure. All fields
    are optional; the console renders what's present. `stage` names
    the phase the probe was in (`validation`, `oauth2_token`,
    `mcp_connect`, `mcp_initialize`, `mcp_notify`, `mcp_list_tools`).
    `oauth2_error` / `oauth2_error_description` mirror RFC 6749 §5.2
    when the customer's auth server returned the standard error
    shape. `http_status` is the upstream status code for transport
    failures. `upstream_body` is a truncated prefix (max ~1 KiB) of
    the upstream response body when the failure isn't structured.
    `field_hint` names a form field (`endpoint`, `transport`,
    `token`, `token_url`, `client_id`, `client_secret`, `scope`)
    the console should highlight so the customer knows what to fix.
    """

    stage: typing.Optional[McpProbeErrorDetailsStage] = None
    http_status: typing.Optional[int] = None
    oauth2error: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="oauth2_error")] = None
    oauth2error_description: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="oauth2_error_description")
    ] = None
    upstream_body: typing.Optional[str] = None
    field_hint: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
