# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations
from ..core.pydantic_utilities import UniversalBaseModel
import typing
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class McpAuth_None(UniversalBaseModel):
    """
    Discriminated union over `type`.
    """

    type: typing.Literal["none"] = "none"

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class McpAuth_Bearer(UniversalBaseModel):
    """
    Discriminated union over `type`.
    """

    type: typing.Literal["bearer"] = "bearer"
    token: typing.Optional[str] = None
    token_set: typing.Optional[bool] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class McpAuth_Oauth2ClientCredentials(UniversalBaseModel):
    """
    Discriminated union over `type`.
    """

    type: typing.Literal["oauth2_client_credentials"] = "oauth2_client_credentials"
    token_url: str
    client_id: str
    client_secret: typing.Optional[str] = None
    client_secret_set: typing.Optional[bool] = None
    scope: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


McpAuth = typing.Union[McpAuth_None, McpAuth_Bearer, McpAuth_Oauth2ClientCredentials]
