# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import pydantic
from .message_role import MessageRole
import typing
import datetime as dt
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class Message(UniversalBaseModel):
    id: str
    conversation_id: str = pydantic.Field()
    """
    Prefixed wire identifier (`conv_<26 char Crockford base32>`)
    of the parent conversation.
    """

    role: MessageRole
    content: str
    tool_name: typing.Optional[str] = None
    tool_args: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = None
    tool_result: typing.Optional[typing.Optional[typing.Any]] = pydantic.Field(default=None)
    """
    Arbitrary JSON value returned by the tool (object, array, string, or primitive).
    """

    started_at: dt.datetime
    ended_at: typing.Optional[dt.datetime] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
