# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import pydantic
from .phone_number_source import PhoneNumberSource
import typing
from .phone_number_capability import PhoneNumberCapability
import datetime as dt
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class PhoneNumber(UniversalBaseModel):
    """
    A phone number in the workspace inventory. Bound to an agent via
    `agent_id`; unbound numbers are valid but non-functional until
    assigned.
    """

    id: str = pydantic.Field()
    """
    Prefixed wire identifier (`phone_<26 char Crockford base32>`).
    URL paths accept only this
    prefixed form; legacy UUID path parameters are rejected with
    404.
    """

    e164: str = pydantic.Field()
    """
    The phone number in E.164 format (e.g. `+12025551234`).
    """

    source: PhoneNumberSource
    label: typing.Optional[str] = pydantic.Field(default=None)
    """
    Optional human-readable label set by the customer.
    """

    trunk_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    ID of the SIP trunk backing this number, if applicable.
    """

    agent_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    ID of the agent that answers calls to this number. Null when unbound.
    """

    capabilities: typing.List[PhoneNumberCapability] = pydantic.Field()
    """
    What this number can do.
    """

    livekit_phone_number_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    LiveKit's own phone number ID (populated for `source=livekit` only).
    """

    created_at: dt.datetime = pydantic.Field()
    """
    When the number was imported.
    """

    updated_at: dt.datetime = pydantic.Field()
    """
    When the number was last modified.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
