# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import datetime as dt
import typing
from .refresh_history_entry_status import RefreshHistoryEntryStatus
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class RefreshHistoryEntry(UniversalBaseModel):
    """
    One auto-refresh attempt. `running` only appears mid-tick;
    terminal values are the ones the drawer renders.
    """

    id: str
    document_id: str
    started_at: dt.datetime
    finished_at: typing.Optional[dt.datetime] = None
    status: RefreshHistoryEntryStatus
    error: typing.Optional[str] = None
    previous_hash: typing.Optional[str] = None
    new_hash: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
