# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
import datetime as dt
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class RefreshConfig(UniversalBaseModel):
    """
    Per-document auto-refresh state. Only populated
    for url-sourced documents; file and text rows omit this and
    the console's auto-refresh panel hides accordingly.
    """

    enabled: bool
    interval_days: int
    auto_remove_enabled: bool
    last_refreshed_at: typing.Optional[dt.datetime] = None
    consecutive_fetch_failures: int

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
