# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import pydantic
import typing
from .retrieval_log_result import RetrievalLogResult
import datetime as dt
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class RetrievalLogEntry(UniversalBaseModel):
    """
    One `search_knowledge` invocation recorded against a
    conversation. Powers the Retrieval panel on the conversation
    detail view.
    """

    id: str
    conversation_id: str = pydantic.Field()
    """
    Prefixed wire identifier (`conv_<26 char Crockford base32>`)
    of the conversation.
    """

    query: str
    results: typing.List[RetrievalLogResult]
    top_k: int
    hit_count: int
    created_at: dt.datetime

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
