# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
from .agent_test_run import AgentTestRun
from .agent_test_suite_run import AgentTestSuiteRun
import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class RunBatchResponse(UniversalBaseModel):
    runs: typing.List[AgentTestRun]
    suite_run: typing.Optional[AgentTestSuiteRun] = pydantic.Field(default=None)
    """
    The suite run grouping the queued runs.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
