# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
from .simulation_message_role import SimulationMessageRole
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import typing
import pydantic


class SimulationMessage(UniversalBaseModel):
    """
    One turn in a simulation conversation. `role` is `user` (the AI caller) or `assistant` (the agent).
    """

    role: SimulationMessageRole
    content: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
