# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import pydantic
import typing
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class SimulationToolCall(UniversalBaseModel):
    """
    One tool invocation that occurred during a simulation run.
    `mocked` is true when the call was intercepted by the run's
    mock config; false when the real tool was called or when the
    tool is a system tool.
    """

    turn_index: int = pydantic.Field()
    """
    Zero-based index of the conversation turn in which this call occurred.
    """

    tool_name: str
    args: typing.Optional[typing.Any] = None
    response: typing.Optional[typing.Optional[typing.Any]] = pydantic.Field(default=None)
    """
    Response returned to the agent (absent for system tools that end the call).
    """

    mocked: bool

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
