# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import pydantic
import typing
from .simulation_message import SimulationMessage
from .data_assertion import DataAssertion
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class SimulationConfig(UniversalBaseModel):
    """
    Configuration for a `simulation` test. An AI caller drives a
    multi-turn conversation with the agent according to `scenario`.
    After `max_turns` exchanges (or when the agent ends the call),
    the unified post-call evaluator scores the synthetic transcript
    against the agent's configured evaluation criteria + data
    collection fields. A test passes when no configured criterion
    fails and every `data_assertions` entry passes.
    """

    scenario: str = pydantic.Field()
    """
    Instructions for the AI caller describing who they are and what they want.
    """

    max_turns: typing.Optional[int] = pydantic.Field(default=None)
    """
    Maximum agent turns before the simulation is cut off and judged.
    """

    initial_chat_history: typing.Optional[typing.List[SimulationMessage]] = pydantic.Field(default=None)
    """
    Optional seed conversation that precedes the AI caller's first generated message.
    """

    data_assertions: typing.Optional[typing.List[DataAssertion]] = pydantic.Field(default=None)
    """
    Optional assertions on the LLM-extracted data-collection
    map. Each entry references a key from the agent's
    data_collection config and validates the extracted value.
    The test fails if any assertion fails.
    """

    system_prompt_override: typing.Optional[str] = pydantic.Field(default=None)
    """
    Deprecated. Prefer the run-level `config_override`
    on `POST /v1/agents/{id}/tests/runs`. Still honoured; the
    run-level override wins when both are set. Replaces the
    agent's system prompt for this run only.
    """

    model_override: typing.Optional[str] = pydantic.Field(default=None)
    """
    Deprecated. Prefer the run-level `config_override`
    on `POST /v1/agents/{id}/tests/runs`. Still honoured; the
    run-level override wins when both are set. Overrides the LLM
    model used by the agent for this run only.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
