# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
from .system_builtin import SystemBuiltin
import typing
from .tool_param import ToolParam
import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class SystemToolConfig(UniversalBaseModel):
    """
    Config shape for `kind=system`. The `builtin` value names the
    worker-resident capability; the catalogue served by
    `GET /v1/agents/tools/system-builtins` is the runtime source of truth
    for valid names plus their console-facing labels.
    """

    builtin: SystemBuiltin
    params: typing.Optional[typing.List[ToolParam]] = None
    builtin_config: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = pydantic.Field(default=None)
    """
    Per-builtin extras (e.g. allowed_numbers for transfer_to_number).
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
