# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import typing


class TestStatsBucket(UniversalBaseModel):
    """
    One daily point on the aggregate pass-rate chart.
    """

    day: str = pydantic.Field()
    """
    ISO date (YYYY-MM-DD).
    """

    passed: int
    failed: int
    errored: int

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
