# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
from .mocking_strategy import MockingStrategy
import typing
from .tool_mock import ToolMock
import pydantic
from .no_match_behavior import NoMatchBehavior
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class ToolMockConfig(UniversalBaseModel):
    """
    Controls tool-call interception during a test run.
    """

    strategy: MockingStrategy
    mocks: typing.Optional[typing.List[ToolMock]] = pydantic.Field(default=None)
    """
    Canned responses for specific tools (order matters - first match wins).
    """

    no_match_behavior: NoMatchBehavior

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
