# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import typing


class UpdateBillingContactEmailRequest(UniversalBaseModel):
    """
    Body for PUT /v1/workspaces/current/billing-contact-email.
    """

    email: str = pydantic.Field()
    """
    New billing contact email. Validated as an RFC 5322 address
    (display-name forms are rejected); must be 254 characters
    or fewer. Domain portion is lowercased for storage.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
