# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class UpdateBillingContactNameRequest(UniversalBaseModel):
    """
    Body for PUT /v1/workspaces/current/billing-contact-name. Pass
    `{"name": null}` to clear the override and revert to inheriting
    the workspace name on invoices.
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Billing-contact name override. When non-null, must be
    non-empty after trimming and 256 characters or fewer.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
