# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
from .widget_config_style import WidgetConfigStyle
from .widget_config_theme import WidgetConfigTheme
from .widget_config_avatar import WidgetConfigAvatar
from .widget_config_text import WidgetConfigText
from .widget_config_terms import WidgetConfigTerms
from .widget_config_transcript import WidgetConfigTranscript
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class WidgetConfig(UniversalBaseModel):
    """
    Customer-editable appearance + behaviour payload for the
    embedded `<speechify-agent>` pill: button text, avatar style,
    orb colours, terms-and-conditions markdown, transcript display.
    Every field is optional - empty fields fall back to the
    widget's compile-time defaults.
    """

    version: typing.Optional[int] = None
    style: typing.Optional[WidgetConfigStyle] = None
    theme: typing.Optional[WidgetConfigTheme] = None
    avatar: typing.Optional[WidgetConfigAvatar] = None
    text: typing.Optional[WidgetConfigText] = None
    terms: typing.Optional[WidgetConfigTerms] = None
    transcript: typing.Optional[WidgetConfigTranscript] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
