# This file was auto-generated by Fern from our API Definition.

import typing
from ...core.client_wrapper import SyncClientWrapper
from ...core.request_options import RequestOptions
from ...types.list_sip_trunks_response import ListSipTrunksResponse
from ...core.pydantic_utilities import parse_obj_as
from ...errors.unauthorized_error import UnauthorizedError
from json.decoder import JSONDecodeError
from ...core.api_error import ApiError
from ...types.sip_trunk_kind import SipTrunkKind
from ...types.sip_trunk_direction import SipTrunkDirection
from ...types.sip_transport import SipTransport
from ...types.sip_media_encryption import SipMediaEncryption
from ...types.sip_trunk import SipTrunk
from ...errors.bad_request_error import BadRequestError
from ...errors.payment_required_error import PaymentRequiredError
from ...types.error import Error
from ...core.jsonable_encoder import jsonable_encoder
from ...errors.not_found_error import NotFoundError
from ...core.client_wrapper import AsyncClientWrapper

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class SipTrunksClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def list(self, *, request_options: typing.Optional[RequestOptions] = None) -> ListSipTrunksResponse:
        """
        List all SIP trunks in the caller's workspace.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListSipTrunksResponse
            The SIP trunks for the workspace.

        Examples
        --------
        from speechify import Speechify

        client = Speechify(
            token="YOUR_TOKEN",
        )
        client.agent.sip_trunks.list()
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/agents/sip-trunks",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    ListSipTrunksResponse,
                    parse_obj_as(
                        type_=ListSipTrunksResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def create(
        self,
        *,
        name: str,
        kind: SipTrunkKind,
        direction: SipTrunkDirection,
        sip_address: typing.Optional[str] = OMIT,
        auth_username: typing.Optional[str] = OMIT,
        auth_password: typing.Optional[str] = OMIT,
        allowed_addresses: typing.Optional[typing.Sequence[str]] = OMIT,
        destination_country: typing.Optional[str] = OMIT,
        transport: typing.Optional[SipTransport] = OMIT,
        media_encryption: typing.Optional[SipMediaEncryption] = OMIT,
        credentials: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SipTrunk:
        """
        Create a SIP trunk. For `kind=byoc` supply `sip_address` plus
        optional digest credentials and IP allowlist. For `kind=twilio`
        use `ImportPhoneNumber` with a `twilio` spec instead - trunk
        creation is handled automatically. Returns 402 when the workspace
        has reached the 20-trunk cap.

        Parameters
        ----------
        name : str
            Human-readable name for the trunk.

        kind : SipTrunkKind

        direction : SipTrunkDirection

        sip_address : typing.Optional[str]
            SIP endpoint hostname. Required for `kind=byoc`.

        auth_username : typing.Optional[str]
            SIP digest auth username.

        auth_password : typing.Optional[str]
            SIP digest auth password. Write-only.

        allowed_addresses : typing.Optional[typing.Sequence[str]]
            IP / CIDR allowlist for inbound connections. Empty means any source is accepted.

        destination_country : typing.Optional[str]
            ISO 3166-1 alpha-2 country for the outbound dial plan.

        transport : typing.Optional[SipTransport]

        media_encryption : typing.Optional[SipMediaEncryption]

        credentials : typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]]
            Provider-specific credential blob (for future extensibility).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SipTrunk
            The created SIP trunk.

        Examples
        --------
        from speechify import Speechify

        client = Speechify(
            token="YOUR_TOKEN",
        )
        client.agent.sip_trunks.create(
            name="Telnyx BYOC",
            kind="byoc",
            direction="both",
            sip_address="sip.telnyx.com",
            auth_username="myuser",
            auth_password="mypassword",
            transport="auto",
            media_encryption="allow",
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/agents/sip-trunks",
            method="POST",
            json={
                "name": name,
                "kind": kind,
                "direction": direction,
                "sip_address": sip_address,
                "auth_username": auth_username,
                "auth_password": auth_password,
                "allowed_addresses": allowed_addresses,
                "destination_country": destination_country,
                "transport": transport,
                "media_encryption": media_encryption,
                "credentials": credentials,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    SipTrunk,
                    parse_obj_as(
                        type_=SipTrunk,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 400:
                raise BadRequestError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 402:
                raise PaymentRequiredError(
                    typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def get(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> SipTrunk:
        """
        Retrieve a SIP trunk by ID.

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SipTrunk
            The requested SIP trunk.

        Examples
        --------
        from speechify import Speechify

        client = Speechify(
            token="YOUR_TOKEN",
        )
        client.agent.sip_trunks.get(
            id="id",
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/agents/sip-trunks/{jsonable_encoder(id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    SipTrunk,
                    parse_obj_as(
                        type_=SipTrunk,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def delete(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Delete a SIP trunk. This also removes the backing LiveKit inbound
        trunk, outbound trunk, and dispatch rule if they were provisioned
        by us. Phone numbers attached to this trunk are left in place but
        become non-functional until rebound to a new trunk.

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from speechify import Speechify

        client = Speechify(
            token="YOUR_TOKEN",
        )
        client.agent.sip_trunks.delete(
            id="id",
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/agents/sip-trunks/{jsonable_encoder(id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return
            if _response.status_code == 401:
                raise UnauthorizedError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)


class AsyncSipTrunksClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def list(self, *, request_options: typing.Optional[RequestOptions] = None) -> ListSipTrunksResponse:
        """
        List all SIP trunks in the caller's workspace.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListSipTrunksResponse
            The SIP trunks for the workspace.

        Examples
        --------
        import asyncio

        from speechify import AsyncSpeechify

        client = AsyncSpeechify(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.agent.sip_trunks.list()


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/agents/sip-trunks",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    ListSipTrunksResponse,
                    parse_obj_as(
                        type_=ListSipTrunksResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def create(
        self,
        *,
        name: str,
        kind: SipTrunkKind,
        direction: SipTrunkDirection,
        sip_address: typing.Optional[str] = OMIT,
        auth_username: typing.Optional[str] = OMIT,
        auth_password: typing.Optional[str] = OMIT,
        allowed_addresses: typing.Optional[typing.Sequence[str]] = OMIT,
        destination_country: typing.Optional[str] = OMIT,
        transport: typing.Optional[SipTransport] = OMIT,
        media_encryption: typing.Optional[SipMediaEncryption] = OMIT,
        credentials: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SipTrunk:
        """
        Create a SIP trunk. For `kind=byoc` supply `sip_address` plus
        optional digest credentials and IP allowlist. For `kind=twilio`
        use `ImportPhoneNumber` with a `twilio` spec instead - trunk
        creation is handled automatically. Returns 402 when the workspace
        has reached the 20-trunk cap.

        Parameters
        ----------
        name : str
            Human-readable name for the trunk.

        kind : SipTrunkKind

        direction : SipTrunkDirection

        sip_address : typing.Optional[str]
            SIP endpoint hostname. Required for `kind=byoc`.

        auth_username : typing.Optional[str]
            SIP digest auth username.

        auth_password : typing.Optional[str]
            SIP digest auth password. Write-only.

        allowed_addresses : typing.Optional[typing.Sequence[str]]
            IP / CIDR allowlist for inbound connections. Empty means any source is accepted.

        destination_country : typing.Optional[str]
            ISO 3166-1 alpha-2 country for the outbound dial plan.

        transport : typing.Optional[SipTransport]

        media_encryption : typing.Optional[SipMediaEncryption]

        credentials : typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]]
            Provider-specific credential blob (for future extensibility).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SipTrunk
            The created SIP trunk.

        Examples
        --------
        import asyncio

        from speechify import AsyncSpeechify

        client = AsyncSpeechify(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.agent.sip_trunks.create(
                name="Telnyx BYOC",
                kind="byoc",
                direction="both",
                sip_address="sip.telnyx.com",
                auth_username="myuser",
                auth_password="mypassword",
                transport="auto",
                media_encryption="allow",
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/agents/sip-trunks",
            method="POST",
            json={
                "name": name,
                "kind": kind,
                "direction": direction,
                "sip_address": sip_address,
                "auth_username": auth_username,
                "auth_password": auth_password,
                "allowed_addresses": allowed_addresses,
                "destination_country": destination_country,
                "transport": transport,
                "media_encryption": media_encryption,
                "credentials": credentials,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    SipTrunk,
                    parse_obj_as(
                        type_=SipTrunk,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 400:
                raise BadRequestError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 402:
                raise PaymentRequiredError(
                    typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def get(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> SipTrunk:
        """
        Retrieve a SIP trunk by ID.

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SipTrunk
            The requested SIP trunk.

        Examples
        --------
        import asyncio

        from speechify import AsyncSpeechify

        client = AsyncSpeechify(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.agent.sip_trunks.get(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/agents/sip-trunks/{jsonable_encoder(id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    SipTrunk,
                    parse_obj_as(
                        type_=SipTrunk,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def delete(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Delete a SIP trunk. This also removes the backing LiveKit inbound
        trunk, outbound trunk, and dispatch rule if they were provisioned
        by us. Phone numbers attached to this trunk are left in place but
        become non-functional until rebound to a new trunk.

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from speechify import AsyncSpeechify

        client = AsyncSpeechify(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.agent.sip_trunks.delete(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/agents/sip-trunks/{jsonable_encoder(id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return
            if _response.status_code == 401:
                raise UnauthorizedError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)
