# This file was auto-generated by Fern from our API Definition.

import typing
from ...types.scenario_config import ScenarioConfig
from ...types.tool_call_config import ToolCallConfig
from ...types.simulation_config import SimulationConfig

UpdateAgentTestRequestConfig = typing.Union[ScenarioConfig, ToolCallConfig, SimulationConfig]
