# This file was auto-generated by Fern from our API Definition.

from . import audio, voices
from .audio import GetSpeechRequestAudioFormat, GetSpeechRequestModel, GetStreamRequestModel, StreamAudioRequestAccept
from .voices import CreateVoicesRequestGender

__all__ = [
    "CreateVoicesRequestGender",
    "GetSpeechRequestAudioFormat",
    "GetSpeechRequestModel",
    "GetStreamRequestModel",
    "StreamAudioRequestAccept",
    "audio",
    "voices",
]
