# This file was auto-generated by Fern from our API Definition.

import typing
from ...core.client_wrapper import SyncClientWrapper
import datetime as dt
from ...core.request_options import RequestOptions
from ...core.pagination import SyncPager
from ...types.caller import Caller
from ...core.datetime_utils import serialize_datetime
from ...types.list_callers_response import ListCallersResponse
from ...core.pydantic_utilities import parse_obj_as
from ...errors.bad_request_error import BadRequestError
from json.decoder import JSONDecodeError
from ...core.api_error import ApiError
from ...types.get_caller_response import GetCallerResponse
from ...core.jsonable_encoder import jsonable_encoder
from ...errors.not_found_error import NotFoundError
from ...types.delete_caller_response import DeleteCallerResponse
from ...types.caller_memory_item import CallerMemoryItem
from ...types.list_caller_memories_response import ListCallerMemoriesResponse
from ...types.conversation import Conversation
from ...types.list_caller_conversations_response import ListCallerConversationsResponse
from ...core.client_wrapper import AsyncClientWrapper
from ...core.pagination import AsyncPager

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class CallersClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def list(
        self,
        *,
        agent_id: typing.Optional[str] = None,
        q: typing.Optional[str] = None,
        last_seen_after: typing.Optional[dt.datetime] = None,
        cursor: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SyncPager[Caller]:
        """
        List the workspace's callers, ordered by most-recently-seen first.
        A caller is the per-(tenant, agent, identity) entity that owns
        long-term memories and conversation history.

        Parameters
        ----------
        agent_id : typing.Optional[str]
            Narrow the list to callers attached to one agent.

        q : typing.Optional[str]
            Identity-prefix search. Filters to rows where `identity LIKE q + '%'`
            (`%`/`_` characters in the input are escaped as literals).

        last_seen_after : typing.Optional[dt.datetime]
            RFC 3339 timestamp. Narrows to callers active strictly AFTER the
            supplied moment. Useful for "active this week / month" filters.

        cursor : typing.Optional[str]
            Opaque cursor from a prior response's `next_cursor`.

        limit : typing.Optional[int]
            Page size. Defaults to 50; capped at 200.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SyncPager[Caller]
            OK

        Examples
        --------
        from speechify import Speechify

        client = Speechify(
            token="YOUR_TOKEN",
        )
        response = client.agent.callers.list()
        for item in response:
            yield item
        # alternatively, you can paginate page-by-page
        for page in response.iter_pages():
            yield page
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/agents/callers",
            method="GET",
            params={
                "agent_id": agent_id,
                "q": q,
                "last_seen_after": serialize_datetime(last_seen_after) if last_seen_after is not None else None,
                "cursor": cursor,
                "limit": limit,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _parsed_response = typing.cast(
                    ListCallersResponse,
                    parse_obj_as(
                        type_=ListCallersResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                _parsed_next = _parsed_response.next_cursor
                _has_next = _parsed_next is not None and _parsed_next != ""
                _get_next = lambda: self.list(
                    agent_id=agent_id,
                    q=q,
                    last_seen_after=last_seen_after,
                    cursor=_parsed_next,
                    limit=limit,
                    request_options=request_options,
                )
                _items = _parsed_response.callers
                return SyncPager(has_next=_has_next, items=_items, get_next=_get_next)
            if _response.status_code == 400:
                raise BadRequestError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def get(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> GetCallerResponse:
        """
        Fetch a single caller by id. Returns 404 for soft-deleted or
        foreign-tenant rows — GDPR-purged callers appear as "not found"
        to the API.

        Parameters
        ----------
        id : str
            Caller ID.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetCallerResponse
            OK

        Examples
        --------
        from speechify import Speechify

        client = Speechify(
            token="YOUR_TOKEN",
        )
        client.agent.callers.get(
            id="id",
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/agents/callers/{jsonable_encoder(id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    GetCallerResponse,
                    parse_obj_as(
                        type_=GetCallerResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def delete(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> DeleteCallerResponse:
        """
        Soft-delete the caller AND cascade soft-delete every memory row
        pointing at it. Conversations survive (forensic / billing records)
        but their caller pointer surfaces as "deleted" through the API.

        Idempotent — re-deleting an already-purged caller returns
        `{caller_purged: 0, memories_purged: 0}`. Audit row counts
        accompany every response so a privacy operator has direct
        evidence of the purge without re-querying.

        Parameters
        ----------
        id : str
            Caller ID.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DeleteCallerResponse
            Soft-delete completed; row counts in the body.

        Examples
        --------
        from speechify import Speechify

        client = Speechify(
            token="YOUR_TOKEN",
        )
        client.agent.callers.delete(
            id="id",
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/agents/callers/{jsonable_encoder(id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    DeleteCallerResponse,
                    parse_obj_as(
                        type_=DeleteCallerResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def update(
        self,
        id: str,
        *,
        display_name: typing.Optional[str] = OMIT,
        external_ref: typing.Optional[str] = OMIT,
        metadata: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GetCallerResponse:
        """
        Update the customer-editable fields on a caller. PATCH semantics:
        omitted fields are unchanged, present fields overwrite. To clear
        a nullable field (`display_name`, `external_ref`) pass an empty
        string. `metadata` REPLACES the existing JSONB blob when supplied.

        Parameters
        ----------
        id : str
            Caller ID.

        display_name : typing.Optional[str]
            Operator-editable display name. Empty string clears the column.

        external_ref : typing.Optional[str]
            Optional handle into the customer's own CRM. Empty string clears the column.

        metadata : typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]]
            Replacement metadata JSONB. Must not be `null`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetCallerResponse
            The refreshed caller row.

        Examples
        --------
        from speechify import Speechify

        client = Speechify(
            token="YOUR_TOKEN",
        )
        client.agent.callers.update(
            id="id",
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/agents/callers/{jsonable_encoder(id)}",
            method="PATCH",
            json={
                "display_name": display_name,
                "external_ref": external_ref,
                "metadata": metadata,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    GetCallerResponse,
                    parse_obj_as(
                        type_=GetCallerResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 400:
                raise BadRequestError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def list_memories(
        self,
        id: str,
        *,
        cursor: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SyncPager[CallerMemoryItem]:
        """
        List one page of memories belonging to the caller, newest first.
        Soft-deleted memories AND memories whose parent caller is
        soft-deleted are hidden — the GDPR purge semantics require the
        API to behave as if those rows do not exist.

        Parameters
        ----------
        id : str
            Caller ID.

        cursor : typing.Optional[str]
            Opaque cursor from a prior response's `next_cursor`.

        limit : typing.Optional[int]
            Page size. Defaults to 50; capped at 200.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SyncPager[CallerMemoryItem]
            OK

        Examples
        --------
        from speechify import Speechify

        client = Speechify(
            token="YOUR_TOKEN",
        )
        response = client.agent.callers.list_memories(
            id="id",
        )
        for item in response:
            yield item
        # alternatively, you can paginate page-by-page
        for page in response.iter_pages():
            yield page
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/agents/callers/{jsonable_encoder(id)}/memories",
            method="GET",
            params={
                "cursor": cursor,
                "limit": limit,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _parsed_response = typing.cast(
                    ListCallerMemoriesResponse,
                    parse_obj_as(
                        type_=ListCallerMemoriesResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                _parsed_next = _parsed_response.next_cursor
                _has_next = _parsed_next is not None and _parsed_next != ""
                _get_next = lambda: self.list_memories(
                    id,
                    cursor=_parsed_next,
                    limit=limit,
                    request_options=request_options,
                )
                _items = _parsed_response.memories
                return SyncPager(has_next=_has_next, items=_items, get_next=_get_next)
            if _response.status_code == 400:
                raise BadRequestError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def list_conversations(
        self,
        id: str,
        *,
        cursor: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SyncPager[Conversation]:
        """
        List one page of conversations belonging to the caller, newest
        started first. Same wire envelope as the workspace-wide
        `GET /v1/agents/conversations`, narrowed to one caller.

        Parameters
        ----------
        id : str
            Caller ID.

        cursor : typing.Optional[str]
            Opaque cursor from a prior response's `next_cursor`.

        limit : typing.Optional[int]
            Page size. Defaults to 50; capped at 200.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SyncPager[Conversation]
            OK

        Examples
        --------
        from speechify import Speechify

        client = Speechify(
            token="YOUR_TOKEN",
        )
        response = client.agent.callers.list_conversations(
            id="id",
        )
        for item in response:
            yield item
        # alternatively, you can paginate page-by-page
        for page in response.iter_pages():
            yield page
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/agents/callers/{jsonable_encoder(id)}/conversations",
            method="GET",
            params={
                "cursor": cursor,
                "limit": limit,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _parsed_response = typing.cast(
                    ListCallerConversationsResponse,
                    parse_obj_as(
                        type_=ListCallerConversationsResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                _parsed_next = _parsed_response.next_cursor
                _has_next = _parsed_next is not None and _parsed_next != ""
                _get_next = lambda: self.list_conversations(
                    id,
                    cursor=_parsed_next,
                    limit=limit,
                    request_options=request_options,
                )
                _items = _parsed_response.conversations
                return SyncPager(has_next=_has_next, items=_items, get_next=_get_next)
            if _response.status_code == 400:
                raise BadRequestError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)


class AsyncCallersClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def list(
        self,
        *,
        agent_id: typing.Optional[str] = None,
        q: typing.Optional[str] = None,
        last_seen_after: typing.Optional[dt.datetime] = None,
        cursor: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncPager[Caller]:
        """
        List the workspace's callers, ordered by most-recently-seen first.
        A caller is the per-(tenant, agent, identity) entity that owns
        long-term memories and conversation history.

        Parameters
        ----------
        agent_id : typing.Optional[str]
            Narrow the list to callers attached to one agent.

        q : typing.Optional[str]
            Identity-prefix search. Filters to rows where `identity LIKE q + '%'`
            (`%`/`_` characters in the input are escaped as literals).

        last_seen_after : typing.Optional[dt.datetime]
            RFC 3339 timestamp. Narrows to callers active strictly AFTER the
            supplied moment. Useful for "active this week / month" filters.

        cursor : typing.Optional[str]
            Opaque cursor from a prior response's `next_cursor`.

        limit : typing.Optional[int]
            Page size. Defaults to 50; capped at 200.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncPager[Caller]
            OK

        Examples
        --------
        import asyncio

        from speechify import AsyncSpeechify

        client = AsyncSpeechify(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            response = await client.agent.callers.list()
            async for item in response:
                yield item
            # alternatively, you can paginate page-by-page
            async for page in response.iter_pages():
                yield page


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/agents/callers",
            method="GET",
            params={
                "agent_id": agent_id,
                "q": q,
                "last_seen_after": serialize_datetime(last_seen_after) if last_seen_after is not None else None,
                "cursor": cursor,
                "limit": limit,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _parsed_response = typing.cast(
                    ListCallersResponse,
                    parse_obj_as(
                        type_=ListCallersResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                _parsed_next = _parsed_response.next_cursor
                _has_next = _parsed_next is not None and _parsed_next != ""
                _get_next = lambda: self.list(
                    agent_id=agent_id,
                    q=q,
                    last_seen_after=last_seen_after,
                    cursor=_parsed_next,
                    limit=limit,
                    request_options=request_options,
                )
                _items = _parsed_response.callers
                return AsyncPager(has_next=_has_next, items=_items, get_next=_get_next)
            if _response.status_code == 400:
                raise BadRequestError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def get(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> GetCallerResponse:
        """
        Fetch a single caller by id. Returns 404 for soft-deleted or
        foreign-tenant rows — GDPR-purged callers appear as "not found"
        to the API.

        Parameters
        ----------
        id : str
            Caller ID.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetCallerResponse
            OK

        Examples
        --------
        import asyncio

        from speechify import AsyncSpeechify

        client = AsyncSpeechify(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.agent.callers.get(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/agents/callers/{jsonable_encoder(id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    GetCallerResponse,
                    parse_obj_as(
                        type_=GetCallerResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def delete(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> DeleteCallerResponse:
        """
        Soft-delete the caller AND cascade soft-delete every memory row
        pointing at it. Conversations survive (forensic / billing records)
        but their caller pointer surfaces as "deleted" through the API.

        Idempotent — re-deleting an already-purged caller returns
        `{caller_purged: 0, memories_purged: 0}`. Audit row counts
        accompany every response so a privacy operator has direct
        evidence of the purge without re-querying.

        Parameters
        ----------
        id : str
            Caller ID.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DeleteCallerResponse
            Soft-delete completed; row counts in the body.

        Examples
        --------
        import asyncio

        from speechify import AsyncSpeechify

        client = AsyncSpeechify(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.agent.callers.delete(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/agents/callers/{jsonable_encoder(id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    DeleteCallerResponse,
                    parse_obj_as(
                        type_=DeleteCallerResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def update(
        self,
        id: str,
        *,
        display_name: typing.Optional[str] = OMIT,
        external_ref: typing.Optional[str] = OMIT,
        metadata: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GetCallerResponse:
        """
        Update the customer-editable fields on a caller. PATCH semantics:
        omitted fields are unchanged, present fields overwrite. To clear
        a nullable field (`display_name`, `external_ref`) pass an empty
        string. `metadata` REPLACES the existing JSONB blob when supplied.

        Parameters
        ----------
        id : str
            Caller ID.

        display_name : typing.Optional[str]
            Operator-editable display name. Empty string clears the column.

        external_ref : typing.Optional[str]
            Optional handle into the customer's own CRM. Empty string clears the column.

        metadata : typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]]
            Replacement metadata JSONB. Must not be `null`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetCallerResponse
            The refreshed caller row.

        Examples
        --------
        import asyncio

        from speechify import AsyncSpeechify

        client = AsyncSpeechify(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.agent.callers.update(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/agents/callers/{jsonable_encoder(id)}",
            method="PATCH",
            json={
                "display_name": display_name,
                "external_ref": external_ref,
                "metadata": metadata,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    GetCallerResponse,
                    parse_obj_as(
                        type_=GetCallerResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 400:
                raise BadRequestError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def list_memories(
        self,
        id: str,
        *,
        cursor: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncPager[CallerMemoryItem]:
        """
        List one page of memories belonging to the caller, newest first.
        Soft-deleted memories AND memories whose parent caller is
        soft-deleted are hidden — the GDPR purge semantics require the
        API to behave as if those rows do not exist.

        Parameters
        ----------
        id : str
            Caller ID.

        cursor : typing.Optional[str]
            Opaque cursor from a prior response's `next_cursor`.

        limit : typing.Optional[int]
            Page size. Defaults to 50; capped at 200.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncPager[CallerMemoryItem]
            OK

        Examples
        --------
        import asyncio

        from speechify import AsyncSpeechify

        client = AsyncSpeechify(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            response = await client.agent.callers.list_memories(
                id="id",
            )
            async for item in response:
                yield item
            # alternatively, you can paginate page-by-page
            async for page in response.iter_pages():
                yield page


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/agents/callers/{jsonable_encoder(id)}/memories",
            method="GET",
            params={
                "cursor": cursor,
                "limit": limit,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _parsed_response = typing.cast(
                    ListCallerMemoriesResponse,
                    parse_obj_as(
                        type_=ListCallerMemoriesResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                _parsed_next = _parsed_response.next_cursor
                _has_next = _parsed_next is not None and _parsed_next != ""
                _get_next = lambda: self.list_memories(
                    id,
                    cursor=_parsed_next,
                    limit=limit,
                    request_options=request_options,
                )
                _items = _parsed_response.memories
                return AsyncPager(has_next=_has_next, items=_items, get_next=_get_next)
            if _response.status_code == 400:
                raise BadRequestError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def list_conversations(
        self,
        id: str,
        *,
        cursor: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncPager[Conversation]:
        """
        List one page of conversations belonging to the caller, newest
        started first. Same wire envelope as the workspace-wide
        `GET /v1/agents/conversations`, narrowed to one caller.

        Parameters
        ----------
        id : str
            Caller ID.

        cursor : typing.Optional[str]
            Opaque cursor from a prior response's `next_cursor`.

        limit : typing.Optional[int]
            Page size. Defaults to 50; capped at 200.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncPager[Conversation]
            OK

        Examples
        --------
        import asyncio

        from speechify import AsyncSpeechify

        client = AsyncSpeechify(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            response = await client.agent.callers.list_conversations(
                id="id",
            )
            async for item in response:
                yield item
            # alternatively, you can paginate page-by-page
            async for page in response.iter_pages():
                yield page


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/agents/callers/{jsonable_encoder(id)}/conversations",
            method="GET",
            params={
                "cursor": cursor,
                "limit": limit,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _parsed_response = typing.cast(
                    ListCallerConversationsResponse,
                    parse_obj_as(
                        type_=ListCallerConversationsResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                _parsed_next = _parsed_response.next_cursor
                _has_next = _parsed_next is not None and _parsed_next != ""
                _get_next = lambda: self.list_conversations(
                    id,
                    cursor=_parsed_next,
                    limit=limit,
                    request_options=request_options,
                )
                _items = _parsed_response.conversations
                return AsyncPager(has_next=_has_next, items=_items, get_next=_get_next)
            if _response.status_code == 400:
                raise BadRequestError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)
