# This file was auto-generated by Fern from our API Definition.

from ...core.pydantic_utilities import UniversalBaseModel
import typing
import pydantic
import datetime as dt
from ...core.pydantic_utilities import IS_PYDANTIC_V2


class Agent(UniversalBaseModel):
    id: str
    name: str
    slug: str
    prompt: typing.Optional[str] = None
    first_message: typing.Optional[str] = None
    language: str = pydantic.Field()
    """
    ISO 639-1 code, e.g. 'en'.
    """

    llm_model: str = pydantic.Field()
    """
    Chat model slug. Leave empty to use the Speechify default.
    """

    voice_id: str = pydantic.Field()
    """
    Speechify voice slug.
    """

    temperature: float
    config: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = pydantic.Field(default=None)
    """
    Free-form agent config JSON (evaluation_config is read via its own endpoint).
    """

    is_public: bool = pydantic.Field()
    """
    When true, the `<speechify-agent>` web component can start a
    session against this agent without an API key, subject to
    the `allowed_origins` allowlist. When false (default), only
    authenticated callers can start sessions.
    """

    allowed_origins: typing.List[str] = pydantic.Field()
    """
    Exact `Origin` header values (e.g. `https://example.com`)
    that are allowed to start public sessions. Empty array
    with `is_public = true` means any origin is accepted —
    intended for open demos. No subdomain wildcards.
    """

    hostname_allowlist: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Optional per-agent hostname allowlist enforced at
    session-creation time. When set and non-empty, the
    `Origin` header's hostname must be an exact member.
    Bare hostnames only — no scheme, port, or path. Up to
    10 entries. Omit (null) or leave empty for no
    enforcement (public agents accept any hostname).
    """

    memory_enabled: bool = pydantic.Field()
    """
    When true, the post-call extractor writes durable facts about
    each caller; at conversation-start the retriever injects the
    top matches into the system prompt via the `{{memory}}`
    template variable. Defaults to false.
    """

    memory_retention_days: int = pydantic.Field()
    """
    Maximum age (in days) of memories kept and surfaced to the
    retriever. 0 disables the cap. Defaults to 90.
    """

    created_at: dt.datetime
    updated_at: dt.datetime

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
