# This file was auto-generated by Fern from our API Definition.

import typing
from .scenario_config import ScenarioConfig
from .tool_call_config import ToolCallConfig
from .simulation_config import SimulationConfig

AgentTestConfig = typing.Union[ScenarioConfig, ToolCallConfig, SimulationConfig]
