# This file was auto-generated by Fern from our API Definition.

from ...core.pydantic_utilities import UniversalBaseModel
from .test_type import TestType
from .agent_test_config import AgentTestConfig
import pydantic
import typing
from .tool_mock_config import ToolMockConfig
import datetime as dt
from ...core.pydantic_utilities import IS_PYDANTIC_V2


class AgentTest(UniversalBaseModel):
    """
    A configured test against a voice agent. `config` is a
    type-specific document - see `ScenarioConfig`, `ToolCallConfig`,
    and `SimulationConfig` for the per-type shapes (discriminated by `type`).
    """

    id: str
    agent_id: str
    name: str
    description: str
    type: TestType
    config: AgentTestConfig = pydantic.Field()
    """
    Type-specific configuration document.
    """

    tool_mock_config: typing.Optional[ToolMockConfig] = pydantic.Field(default=None)
    """
    Optional tool-mocking config applied during runs of this test.
    """

    variables: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = pydantic.Field(default=None)
    """
    Per-test dynamic-variable overrides. Keys substitute `{{key}}`
    placeholders inside the test config at run-start. Unknown keys
    render as empty string, matching session dispatch behaviour.
    """

    folder_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Folder the test belongs to; null = root (unfiled).
    """

    created_at: dt.datetime
    updated_at: dt.datetime

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
