# This file was auto-generated by Fern from our API Definition.

from ...core.pydantic_utilities import UniversalBaseModel
from .data_collection_field_type import DataCollectionFieldType
from ...core.pydantic_utilities import IS_PYDANTIC_V2
import typing
import pydantic


class DataCollectionField(UniversalBaseModel):
    """
    A structured value the post-call evaluator should extract from the
    transcript. `int` is distinct from `number` so downstream consumers
    receive whole integers without a synthetic decimal.
    """

    key: str
    description: str
    type: DataCollectionFieldType

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
