# This file was auto-generated by Fern from our API Definition.

from ...core.pydantic_utilities import UniversalBaseModel
import typing
from .evaluation import Evaluation
from ...core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class ListEvaluationsResponse(UniversalBaseModel):
    evaluations: typing.List[Evaluation]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
