# This file was auto-generated by Fern from our API Definition.

from ...core.pydantic_utilities import UniversalBaseModel
import pydantic
from .tenant_plan import TenantPlan
from .tenant_data_region import TenantDataRegion
import datetime as dt
from ...core.pydantic_utilities import IS_PYDANTIC_V2
import typing


class Tenant(UniversalBaseModel):
    """
    A workspace the caller belongs to.
    """

    id: str = pydantic.Field()
    """
    Opaque workspace ID.
    """

    name: str = pydantic.Field()
    """
    Display name set by the workspace owner.
    """

    plan: TenantPlan = pydantic.Field()
    """
    Billing plan tier.
    """

    data_region: TenantDataRegion = pydantic.Field()
    """
    Geographic region the workspace's data is pinned to.
    """

    hipaa_mode: bool = pydantic.Field()
    """
    When true, HIPAA-compliant retention and logging is enforced.
    """

    zero_retention: bool = pydantic.Field()
    """
    When true, no transcript / audio payloads are retained server-side.
    """

    created_at: dt.datetime
    updated_at: dt.datetime

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
