# This file was auto-generated by Fern from our API Definition.

from ...core.pydantic_utilities import UniversalBaseModel
from .tool_param_type import ToolParamType
import typing
from ...core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class ToolParam(UniversalBaseModel):
    """
    One argument the LLM can pass when calling the tool. Mirrors the JSON-Schema subset standard function-calling schemas support.
    """

    name: str
    type: ToolParamType
    description: str
    required: bool
    enum: typing.Optional[typing.List[str]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
