# This file was auto-generated by Fern from our API Definition.

from ...core.client_wrapper import SyncClientWrapper
import typing
from ...types.conversation_status import ConversationStatus
from ...types.conversation_transport import ConversationTransport
import datetime as dt
from ...core.request_options import RequestOptions
from ...core.pagination import SyncPager
from ...types.conversation import Conversation
from ...core.datetime_utils import serialize_datetime
from ...types.list_conversations_response import ListConversationsResponse
from ...core.pydantic_utilities import parse_obj_as
from ...errors.unauthorized_error import UnauthorizedError
from json.decoder import JSONDecodeError
from ...core.api_error import ApiError
from ...types.conversation_stats import ConversationStats
from ...types.recent_callee import RecentCallee
from ...types.list_recent_callees_response import ListRecentCalleesResponse
from ...errors.bad_request_error import BadRequestError
from ...core.jsonable_encoder import jsonable_encoder
from ...errors.not_found_error import NotFoundError
from ...types.message import Message
from ...types.list_messages_response import ListMessagesResponse
from ...types.list_evaluations_response import ListEvaluationsResponse
from ...types.webhook_delivery import WebhookDelivery
from ...types.list_webhook_deliveries_response import ListWebhookDeliveriesResponse
from ...types.retrieval_log_entry import RetrievalLogEntry
from ...types.list_retrieval_logs_response import ListRetrievalLogsResponse
from ...types.list_memories_response import ListMemoriesResponse
from ...core.client_wrapper import AsyncClientWrapper
from ...core.pagination import AsyncPager


class ConversationsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def list(
        self,
        *,
        cursor: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        agent_id: typing.Optional[str] = None,
        status: typing.Optional[ConversationStatus] = None,
        transport: typing.Optional[ConversationTransport] = None,
        caller_identity: typing.Optional[str] = None,
        search: typing.Optional[str] = None,
        started_after: typing.Optional[dt.datetime] = None,
        started_before: typing.Optional[dt.datetime] = None,
        duration_min_ms: typing.Optional[int] = None,
        duration_max_ms: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SyncPager[Conversation]:
        """
        List conversations owned by the caller, ordered by most recent.
        Cursor-paginated: omit `cursor` to fetch the first page; pass the
        previous response's `next_cursor` back to fetch the next page.
        Walk pages while `has_more` is true.

        Parameters
        ----------
        cursor : typing.Optional[str]
            Opaque pagination cursor from a previous response.

        limit : typing.Optional[int]
            Max conversations per page (default 50, max 200).

        agent_id : typing.Optional[str]
            Filter to conversations for this agent.

        status : typing.Optional[ConversationStatus]
            Filter by conversation status.

        transport : typing.Optional[ConversationTransport]
            Filter by transport.

        caller_identity : typing.Optional[str]
            Filter by caller identity.

        search : typing.Optional[str]
            Free-text search across conversation content.

        started_after : typing.Optional[dt.datetime]
            Only conversations started at or after this RFC 3339 timestamp.

        started_before : typing.Optional[dt.datetime]
            Only conversations started at or before this RFC 3339 timestamp.

        duration_min_ms : typing.Optional[int]
            Minimum conversation duration in milliseconds.

        duration_max_ms : typing.Optional[int]
            Maximum conversation duration in milliseconds.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SyncPager[Conversation]
            A list of conversations.

        Examples
        --------
        from speechify import Speechify

        client = Speechify(
            token="YOUR_TOKEN",
        )
        response = client.agent.conversations.list()
        for item in response:
            yield item
        # alternatively, you can paginate page-by-page
        for page in response.iter_pages():
            yield page
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/agents/conversations",
            method="GET",
            params={
                "cursor": cursor,
                "limit": limit,
                "agent_id": agent_id,
                "status": status,
                "transport": transport,
                "caller_identity": caller_identity,
                "search": search,
                "started_after": serialize_datetime(started_after) if started_after is not None else None,
                "started_before": serialize_datetime(started_before) if started_before is not None else None,
                "duration_min_ms": duration_min_ms,
                "duration_max_ms": duration_max_ms,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _parsed_response = typing.cast(
                    ListConversationsResponse,
                    parse_obj_as(
                        type_=ListConversationsResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                _parsed_next = _parsed_response.next_cursor
                _has_next = _parsed_next is not None and _parsed_next != ""
                _get_next = lambda: self.list(
                    cursor=_parsed_next,
                    limit=limit,
                    agent_id=agent_id,
                    status=status,
                    transport=transport,
                    caller_identity=caller_identity,
                    search=search,
                    started_after=started_after,
                    started_before=started_before,
                    duration_min_ms=duration_min_ms,
                    duration_max_ms=duration_max_ms,
                    request_options=request_options,
                )
                _items = _parsed_response.conversations
                return SyncPager(has_next=_has_next, items=_items, get_next=_get_next)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def stats(
        self,
        *,
        agent_id: typing.Optional[str] = None,
        status: typing.Optional[ConversationStatus] = None,
        transport: typing.Optional[ConversationTransport] = None,
        caller_identity: typing.Optional[str] = None,
        search: typing.Optional[str] = None,
        started_after: typing.Optional[dt.datetime] = None,
        started_before: typing.Optional[dt.datetime] = None,
        duration_min_ms: typing.Optional[int] = None,
        duration_max_ms: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ConversationStats:
        """
        Aggregated counts and averages over the caller's conversations, scoped by the same filters as the list endpoint.

        Parameters
        ----------
        agent_id : typing.Optional[str]
            Filter to conversations for this agent.

        status : typing.Optional[ConversationStatus]
            Filter by conversation status.

        transport : typing.Optional[ConversationTransport]
            Filter by transport.

        caller_identity : typing.Optional[str]
            Filter by caller identity.

        search : typing.Optional[str]
            Free-text search across conversation content.

        started_after : typing.Optional[dt.datetime]
            Only conversations started at or after this RFC 3339 timestamp.

        started_before : typing.Optional[dt.datetime]
            Only conversations started at or before this RFC 3339 timestamp.

        duration_min_ms : typing.Optional[int]
            Minimum conversation duration in milliseconds.

        duration_max_ms : typing.Optional[int]
            Maximum conversation duration in milliseconds.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ConversationStats
            Stats for the matched conversations.

        Examples
        --------
        from speechify import Speechify

        client = Speechify(
            token="YOUR_TOKEN",
        )
        client.agent.conversations.stats()
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/agents/conversations/stats",
            method="GET",
            params={
                "agent_id": agent_id,
                "status": status,
                "transport": transport,
                "caller_identity": caller_identity,
                "search": search,
                "started_after": serialize_datetime(started_after) if started_after is not None else None,
                "started_before": serialize_datetime(started_before) if started_before is not None else None,
                "duration_min_ms": duration_min_ms,
                "duration_max_ms": duration_max_ms,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    ConversationStats,
                    parse_obj_as(
                        type_=ConversationStats,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def recent_callees(
        self,
        *,
        cursor: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SyncPager[RecentCallee]:
        """
        Distinct phone numbers the caller's workspace has dialled on
        outbound calls, ordered by most recent. Feeds the batch-calls
        composer's "Suggested from history" surface. Cursor-paginated:
        omit `cursor` to fetch the first page. Default page size is 50
        and max is 200. Walk pages while `has_more` is true.

        Parameters
        ----------
        cursor : typing.Optional[str]
            Opaque pagination cursor from a previous response.

        limit : typing.Optional[int]
            Max number of distinct phone numbers per page. Defaults to 50; clamped to 200.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SyncPager[RecentCallee]
            Recent callees for the caller's workspace.

        Examples
        --------
        from speechify import Speechify

        client = Speechify(
            token="YOUR_TOKEN",
        )
        response = client.agent.conversations.recent_callees()
        for item in response:
            yield item
        # alternatively, you can paginate page-by-page
        for page in response.iter_pages():
            yield page
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/agents/conversations/recent-callees",
            method="GET",
            params={
                "cursor": cursor,
                "limit": limit,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _parsed_response = typing.cast(
                    ListRecentCalleesResponse,
                    parse_obj_as(
                        type_=ListRecentCalleesResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                _parsed_next = _parsed_response.next_cursor
                _has_next = _parsed_next is not None and _parsed_next != ""
                _get_next = lambda: self.recent_callees(
                    cursor=_parsed_next,
                    limit=limit,
                    request_options=request_options,
                )
                _items = _parsed_response.callees
                return SyncPager(has_next=_has_next, items=_items, get_next=_get_next)
            if _response.status_code == 400:
                raise BadRequestError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def get(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> Conversation:
        """
        Retrieve a conversation by ID.

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Conversation
            The requested conversation.

        Examples
        --------
        from speechify import Speechify

        client = Speechify(
            token="YOUR_TOKEN",
        )
        client.agent.conversations.get(
            id="id",
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/agents/conversations/{jsonable_encoder(id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    Conversation,
                    parse_obj_as(
                        type_=Conversation,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def list_messages(
        self,
        id: str,
        *,
        cursor: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SyncPager[Message]:
        """
        Retrieve the transcript for a conversation in started_at order
        (oldest first). Cursor-paginated: omit `cursor` to fetch the
        first page. Default page size is 50 and max is 200. Walk pages
        while `has_more` is true.

        Parameters
        ----------
        id : str

        cursor : typing.Optional[str]
            Opaque pagination cursor from a previous response.

        limit : typing.Optional[int]
            Max messages per page (default 50, max 200).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SyncPager[Message]
            The messages for the conversation.

        Examples
        --------
        from speechify import Speechify

        client = Speechify(
            token="YOUR_TOKEN",
        )
        response = client.agent.conversations.list_messages(
            id="id",
        )
        for item in response:
            yield item
        # alternatively, you can paginate page-by-page
        for page in response.iter_pages():
            yield page
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/agents/conversations/{jsonable_encoder(id)}/messages",
            method="GET",
            params={
                "cursor": cursor,
                "limit": limit,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _parsed_response = typing.cast(
                    ListMessagesResponse,
                    parse_obj_as(
                        type_=ListMessagesResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                _parsed_next = _parsed_response.next_cursor
                _has_next = _parsed_next is not None and _parsed_next != ""
                _get_next = lambda: self.list_messages(
                    id,
                    cursor=_parsed_next,
                    limit=limit,
                    request_options=request_options,
                )
                _items = _parsed_response.messages
                return SyncPager(has_next=_has_next, items=_items, get_next=_get_next)
            if _response.status_code == 400:
                raise BadRequestError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def list_evaluations(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ListEvaluationsResponse:
        """
        Retrieve post-call evaluation results for a conversation.

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListEvaluationsResponse
            The evaluations for the conversation.

        Examples
        --------
        from speechify import Speechify

        client = Speechify(
            token="YOUR_TOKEN",
        )
        client.agent.conversations.list_evaluations(
            id="id",
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/agents/conversations/{jsonable_encoder(id)}/evaluations",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    ListEvaluationsResponse,
                    parse_obj_as(
                        type_=ListEvaluationsResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def stream_recording(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Iterator[bytes]:
        """
        Proxy the GCS-stored audio recording for a conversation through
        the Cloud Run service identity. Returns OGG/Opus bytes (LiveKit
        room-composite egress default). The response is streamed so a
        long recording does not buffer in memory; `<audio src>` consumers
        can seek directly. Only present when the agent had
        `save_audio_recording` enabled at session start.

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration. You can pass in configuration such as `chunk_size`, and more to customize the request and response.

        Yields
        ------
        typing.Iterator[bytes]
            The recorded audio.

        Examples
        --------
        from speechify import Speechify

        client = Speechify(
            token="YOUR_TOKEN",
        )
        client.agent.conversations.stream_recording(
            id="id",
        )
        """
        with self._client_wrapper.httpx_client.stream(
            f"v1/agents/conversations/{jsonable_encoder(id)}/recording",
            method="GET",
            request_options=request_options,
        ) as _response:
            try:
                if 200 <= _response.status_code < 300:
                    _chunk_size = request_options.get("chunk_size", None) if request_options is not None else None
                    for _chunk in _response.iter_bytes(chunk_size=_chunk_size):
                        yield _chunk
                    return
                _response.read()
                if _response.status_code == 401:
                    raise UnauthorizedError(
                        typing.cast(
                            typing.Optional[typing.Any],
                            parse_obj_as(
                                type_=typing.Optional[typing.Any],  # type: ignore
                                object_=_response.json(),
                            ),
                        )
                    )
                if _response.status_code == 404:
                    raise NotFoundError(
                        typing.cast(
                            typing.Optional[typing.Any],
                            parse_obj_as(
                                type_=typing.Optional[typing.Any],  # type: ignore
                                object_=_response.json(),
                            ),
                        )
                    )
                _response_json = _response.json()
            except JSONDecodeError:
                raise ApiError(status_code=_response.status_code, body=_response.text)
            raise ApiError(status_code=_response.status_code, body=_response_json)

    def list_webhook_deliveries(
        self,
        id: str,
        *,
        cursor: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SyncPager[WebhookDelivery]:
        """
        List post-call webhook delivery attempts for a conversation,
        newest first. Rows appear once the LiveKit `room_finished`
        webhook has fired and the post-call webhook has been
        dispatched to the agent's configured URL. One row per
        `(conversation, webhook-url)`, updated in place across retries.
        Cursor-paginated: omit `cursor` to fetch the first page.
        Default page size is 50 and max is 200. Walk pages while
        `has_more` is true.

        Parameters
        ----------
        id : str

        cursor : typing.Optional[str]
            Opaque pagination cursor from a previous response.

        limit : typing.Optional[int]
            Max deliveries per page (default 50, max 200).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SyncPager[WebhookDelivery]
            The post-call webhook deliveries for the conversation.

        Examples
        --------
        from speechify import Speechify

        client = Speechify(
            token="YOUR_TOKEN",
        )
        response = client.agent.conversations.list_webhook_deliveries(
            id="id",
        )
        for item in response:
            yield item
        # alternatively, you can paginate page-by-page
        for page in response.iter_pages():
            yield page
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/agents/conversations/{jsonable_encoder(id)}/webhook-deliveries",
            method="GET",
            params={
                "cursor": cursor,
                "limit": limit,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _parsed_response = typing.cast(
                    ListWebhookDeliveriesResponse,
                    parse_obj_as(
                        type_=ListWebhookDeliveriesResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                _parsed_next = _parsed_response.next_cursor
                _has_next = _parsed_next is not None and _parsed_next != ""
                _get_next = lambda: self.list_webhook_deliveries(
                    id,
                    cursor=_parsed_next,
                    limit=limit,
                    request_options=request_options,
                )
                _items = _parsed_response.deliveries
                return SyncPager(has_next=_has_next, items=_items, get_next=_get_next)
            if _response.status_code == 400:
                raise BadRequestError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def list_retrieval_log(
        self,
        id: str,
        *,
        cursor: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SyncPager[RetrievalLogEntry]:
        """
        Per-conversation retrieval log, newest first — one row per
        `search_knowledge` invocation made during the call. Each entry
        records the query, ranked chunks (denormalised so deletions
        don't render history unreadable), `top_k`, and hit count.
        Powers the Retrieval panel on the conversation detail view.
        Cursor-paginated: omit `cursor` to fetch the first page.
        Default page size is 50 and max is 200. Walk pages while
        `has_more` is true.

        Parameters
        ----------
        id : str

        cursor : typing.Optional[str]
            Opaque pagination cursor from a previous response.

        limit : typing.Optional[int]
            Max retrieval log entries per page (default 50, max 200).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SyncPager[RetrievalLogEntry]
            The retrieval log entries for the conversation.

        Examples
        --------
        from speechify import Speechify

        client = Speechify(
            token="YOUR_TOKEN",
        )
        response = client.agent.conversations.list_retrieval_log(
            id="id",
        )
        for item in response:
            yield item
        # alternatively, you can paginate page-by-page
        for page in response.iter_pages():
            yield page
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/agents/conversations/{jsonable_encoder(id)}/retrieval-log",
            method="GET",
            params={
                "cursor": cursor,
                "limit": limit,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _parsed_response = typing.cast(
                    ListRetrievalLogsResponse,
                    parse_obj_as(
                        type_=ListRetrievalLogsResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                _parsed_next = _parsed_response.next_cursor
                _has_next = _parsed_next is not None and _parsed_next != ""
                _get_next = lambda: self.list_retrieval_log(
                    id,
                    cursor=_parsed_next,
                    limit=limit,
                    request_options=request_options,
                )
                _items = _parsed_response.entries
                return SyncPager(has_next=_has_next, items=_items, get_next=_get_next)
            if _response.status_code == 400:
                raise BadRequestError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def list_memories(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ListMemoriesResponse:
        """
        List memories extracted from a specific conversation.

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListMemoriesResponse
            Memories written during this conversation.

        Examples
        --------
        from speechify import Speechify

        client = Speechify(
            token="YOUR_TOKEN",
        )
        client.agent.conversations.list_memories(
            id="id",
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/agents/conversations/{jsonable_encoder(id)}/memories",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    ListMemoriesResponse,
                    parse_obj_as(
                        type_=ListMemoriesResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)


class AsyncConversationsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def list(
        self,
        *,
        cursor: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        agent_id: typing.Optional[str] = None,
        status: typing.Optional[ConversationStatus] = None,
        transport: typing.Optional[ConversationTransport] = None,
        caller_identity: typing.Optional[str] = None,
        search: typing.Optional[str] = None,
        started_after: typing.Optional[dt.datetime] = None,
        started_before: typing.Optional[dt.datetime] = None,
        duration_min_ms: typing.Optional[int] = None,
        duration_max_ms: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncPager[Conversation]:
        """
        List conversations owned by the caller, ordered by most recent.
        Cursor-paginated: omit `cursor` to fetch the first page; pass the
        previous response's `next_cursor` back to fetch the next page.
        Walk pages while `has_more` is true.

        Parameters
        ----------
        cursor : typing.Optional[str]
            Opaque pagination cursor from a previous response.

        limit : typing.Optional[int]
            Max conversations per page (default 50, max 200).

        agent_id : typing.Optional[str]
            Filter to conversations for this agent.

        status : typing.Optional[ConversationStatus]
            Filter by conversation status.

        transport : typing.Optional[ConversationTransport]
            Filter by transport.

        caller_identity : typing.Optional[str]
            Filter by caller identity.

        search : typing.Optional[str]
            Free-text search across conversation content.

        started_after : typing.Optional[dt.datetime]
            Only conversations started at or after this RFC 3339 timestamp.

        started_before : typing.Optional[dt.datetime]
            Only conversations started at or before this RFC 3339 timestamp.

        duration_min_ms : typing.Optional[int]
            Minimum conversation duration in milliseconds.

        duration_max_ms : typing.Optional[int]
            Maximum conversation duration in milliseconds.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncPager[Conversation]
            A list of conversations.

        Examples
        --------
        import asyncio

        from speechify import AsyncSpeechify

        client = AsyncSpeechify(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            response = await client.agent.conversations.list()
            async for item in response:
                yield item
            # alternatively, you can paginate page-by-page
            async for page in response.iter_pages():
                yield page


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/agents/conversations",
            method="GET",
            params={
                "cursor": cursor,
                "limit": limit,
                "agent_id": agent_id,
                "status": status,
                "transport": transport,
                "caller_identity": caller_identity,
                "search": search,
                "started_after": serialize_datetime(started_after) if started_after is not None else None,
                "started_before": serialize_datetime(started_before) if started_before is not None else None,
                "duration_min_ms": duration_min_ms,
                "duration_max_ms": duration_max_ms,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _parsed_response = typing.cast(
                    ListConversationsResponse,
                    parse_obj_as(
                        type_=ListConversationsResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                _parsed_next = _parsed_response.next_cursor
                _has_next = _parsed_next is not None and _parsed_next != ""
                _get_next = lambda: self.list(
                    cursor=_parsed_next,
                    limit=limit,
                    agent_id=agent_id,
                    status=status,
                    transport=transport,
                    caller_identity=caller_identity,
                    search=search,
                    started_after=started_after,
                    started_before=started_before,
                    duration_min_ms=duration_min_ms,
                    duration_max_ms=duration_max_ms,
                    request_options=request_options,
                )
                _items = _parsed_response.conversations
                return AsyncPager(has_next=_has_next, items=_items, get_next=_get_next)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def stats(
        self,
        *,
        agent_id: typing.Optional[str] = None,
        status: typing.Optional[ConversationStatus] = None,
        transport: typing.Optional[ConversationTransport] = None,
        caller_identity: typing.Optional[str] = None,
        search: typing.Optional[str] = None,
        started_after: typing.Optional[dt.datetime] = None,
        started_before: typing.Optional[dt.datetime] = None,
        duration_min_ms: typing.Optional[int] = None,
        duration_max_ms: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ConversationStats:
        """
        Aggregated counts and averages over the caller's conversations, scoped by the same filters as the list endpoint.

        Parameters
        ----------
        agent_id : typing.Optional[str]
            Filter to conversations for this agent.

        status : typing.Optional[ConversationStatus]
            Filter by conversation status.

        transport : typing.Optional[ConversationTransport]
            Filter by transport.

        caller_identity : typing.Optional[str]
            Filter by caller identity.

        search : typing.Optional[str]
            Free-text search across conversation content.

        started_after : typing.Optional[dt.datetime]
            Only conversations started at or after this RFC 3339 timestamp.

        started_before : typing.Optional[dt.datetime]
            Only conversations started at or before this RFC 3339 timestamp.

        duration_min_ms : typing.Optional[int]
            Minimum conversation duration in milliseconds.

        duration_max_ms : typing.Optional[int]
            Maximum conversation duration in milliseconds.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ConversationStats
            Stats for the matched conversations.

        Examples
        --------
        import asyncio

        from speechify import AsyncSpeechify

        client = AsyncSpeechify(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.agent.conversations.stats()


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/agents/conversations/stats",
            method="GET",
            params={
                "agent_id": agent_id,
                "status": status,
                "transport": transport,
                "caller_identity": caller_identity,
                "search": search,
                "started_after": serialize_datetime(started_after) if started_after is not None else None,
                "started_before": serialize_datetime(started_before) if started_before is not None else None,
                "duration_min_ms": duration_min_ms,
                "duration_max_ms": duration_max_ms,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    ConversationStats,
                    parse_obj_as(
                        type_=ConversationStats,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def recent_callees(
        self,
        *,
        cursor: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncPager[RecentCallee]:
        """
        Distinct phone numbers the caller's workspace has dialled on
        outbound calls, ordered by most recent. Feeds the batch-calls
        composer's "Suggested from history" surface. Cursor-paginated:
        omit `cursor` to fetch the first page. Default page size is 50
        and max is 200. Walk pages while `has_more` is true.

        Parameters
        ----------
        cursor : typing.Optional[str]
            Opaque pagination cursor from a previous response.

        limit : typing.Optional[int]
            Max number of distinct phone numbers per page. Defaults to 50; clamped to 200.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncPager[RecentCallee]
            Recent callees for the caller's workspace.

        Examples
        --------
        import asyncio

        from speechify import AsyncSpeechify

        client = AsyncSpeechify(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            response = await client.agent.conversations.recent_callees()
            async for item in response:
                yield item
            # alternatively, you can paginate page-by-page
            async for page in response.iter_pages():
                yield page


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/agents/conversations/recent-callees",
            method="GET",
            params={
                "cursor": cursor,
                "limit": limit,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _parsed_response = typing.cast(
                    ListRecentCalleesResponse,
                    parse_obj_as(
                        type_=ListRecentCalleesResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                _parsed_next = _parsed_response.next_cursor
                _has_next = _parsed_next is not None and _parsed_next != ""
                _get_next = lambda: self.recent_callees(
                    cursor=_parsed_next,
                    limit=limit,
                    request_options=request_options,
                )
                _items = _parsed_response.callees
                return AsyncPager(has_next=_has_next, items=_items, get_next=_get_next)
            if _response.status_code == 400:
                raise BadRequestError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def get(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> Conversation:
        """
        Retrieve a conversation by ID.

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Conversation
            The requested conversation.

        Examples
        --------
        import asyncio

        from speechify import AsyncSpeechify

        client = AsyncSpeechify(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.agent.conversations.get(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/agents/conversations/{jsonable_encoder(id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    Conversation,
                    parse_obj_as(
                        type_=Conversation,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def list_messages(
        self,
        id: str,
        *,
        cursor: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncPager[Message]:
        """
        Retrieve the transcript for a conversation in started_at order
        (oldest first). Cursor-paginated: omit `cursor` to fetch the
        first page. Default page size is 50 and max is 200. Walk pages
        while `has_more` is true.

        Parameters
        ----------
        id : str

        cursor : typing.Optional[str]
            Opaque pagination cursor from a previous response.

        limit : typing.Optional[int]
            Max messages per page (default 50, max 200).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncPager[Message]
            The messages for the conversation.

        Examples
        --------
        import asyncio

        from speechify import AsyncSpeechify

        client = AsyncSpeechify(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            response = await client.agent.conversations.list_messages(
                id="id",
            )
            async for item in response:
                yield item
            # alternatively, you can paginate page-by-page
            async for page in response.iter_pages():
                yield page


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/agents/conversations/{jsonable_encoder(id)}/messages",
            method="GET",
            params={
                "cursor": cursor,
                "limit": limit,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _parsed_response = typing.cast(
                    ListMessagesResponse,
                    parse_obj_as(
                        type_=ListMessagesResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                _parsed_next = _parsed_response.next_cursor
                _has_next = _parsed_next is not None and _parsed_next != ""
                _get_next = lambda: self.list_messages(
                    id,
                    cursor=_parsed_next,
                    limit=limit,
                    request_options=request_options,
                )
                _items = _parsed_response.messages
                return AsyncPager(has_next=_has_next, items=_items, get_next=_get_next)
            if _response.status_code == 400:
                raise BadRequestError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def list_evaluations(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ListEvaluationsResponse:
        """
        Retrieve post-call evaluation results for a conversation.

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListEvaluationsResponse
            The evaluations for the conversation.

        Examples
        --------
        import asyncio

        from speechify import AsyncSpeechify

        client = AsyncSpeechify(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.agent.conversations.list_evaluations(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/agents/conversations/{jsonable_encoder(id)}/evaluations",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    ListEvaluationsResponse,
                    parse_obj_as(
                        type_=ListEvaluationsResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def stream_recording(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.AsyncIterator[bytes]:
        """
        Proxy the GCS-stored audio recording for a conversation through
        the Cloud Run service identity. Returns OGG/Opus bytes (LiveKit
        room-composite egress default). The response is streamed so a
        long recording does not buffer in memory; `<audio src>` consumers
        can seek directly. Only present when the agent had
        `save_audio_recording` enabled at session start.

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration. You can pass in configuration such as `chunk_size`, and more to customize the request and response.

        Yields
        ------
        typing.AsyncIterator[bytes]
            The recorded audio.

        Examples
        --------
        import asyncio

        from speechify import AsyncSpeechify

        client = AsyncSpeechify(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.agent.conversations.stream_recording(
                id="id",
            )


        asyncio.run(main())
        """
        async with self._client_wrapper.httpx_client.stream(
            f"v1/agents/conversations/{jsonable_encoder(id)}/recording",
            method="GET",
            request_options=request_options,
        ) as _response:
            try:
                if 200 <= _response.status_code < 300:
                    _chunk_size = request_options.get("chunk_size", None) if request_options is not None else None
                    async for _chunk in _response.aiter_bytes(chunk_size=_chunk_size):
                        yield _chunk
                    return
                await _response.aread()
                if _response.status_code == 401:
                    raise UnauthorizedError(
                        typing.cast(
                            typing.Optional[typing.Any],
                            parse_obj_as(
                                type_=typing.Optional[typing.Any],  # type: ignore
                                object_=_response.json(),
                            ),
                        )
                    )
                if _response.status_code == 404:
                    raise NotFoundError(
                        typing.cast(
                            typing.Optional[typing.Any],
                            parse_obj_as(
                                type_=typing.Optional[typing.Any],  # type: ignore
                                object_=_response.json(),
                            ),
                        )
                    )
                _response_json = _response.json()
            except JSONDecodeError:
                raise ApiError(status_code=_response.status_code, body=_response.text)
            raise ApiError(status_code=_response.status_code, body=_response_json)

    async def list_webhook_deliveries(
        self,
        id: str,
        *,
        cursor: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncPager[WebhookDelivery]:
        """
        List post-call webhook delivery attempts for a conversation,
        newest first. Rows appear once the LiveKit `room_finished`
        webhook has fired and the post-call webhook has been
        dispatched to the agent's configured URL. One row per
        `(conversation, webhook-url)`, updated in place across retries.
        Cursor-paginated: omit `cursor` to fetch the first page.
        Default page size is 50 and max is 200. Walk pages while
        `has_more` is true.

        Parameters
        ----------
        id : str

        cursor : typing.Optional[str]
            Opaque pagination cursor from a previous response.

        limit : typing.Optional[int]
            Max deliveries per page (default 50, max 200).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncPager[WebhookDelivery]
            The post-call webhook deliveries for the conversation.

        Examples
        --------
        import asyncio

        from speechify import AsyncSpeechify

        client = AsyncSpeechify(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            response = await client.agent.conversations.list_webhook_deliveries(
                id="id",
            )
            async for item in response:
                yield item
            # alternatively, you can paginate page-by-page
            async for page in response.iter_pages():
                yield page


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/agents/conversations/{jsonable_encoder(id)}/webhook-deliveries",
            method="GET",
            params={
                "cursor": cursor,
                "limit": limit,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _parsed_response = typing.cast(
                    ListWebhookDeliveriesResponse,
                    parse_obj_as(
                        type_=ListWebhookDeliveriesResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                _parsed_next = _parsed_response.next_cursor
                _has_next = _parsed_next is not None and _parsed_next != ""
                _get_next = lambda: self.list_webhook_deliveries(
                    id,
                    cursor=_parsed_next,
                    limit=limit,
                    request_options=request_options,
                )
                _items = _parsed_response.deliveries
                return AsyncPager(has_next=_has_next, items=_items, get_next=_get_next)
            if _response.status_code == 400:
                raise BadRequestError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def list_retrieval_log(
        self,
        id: str,
        *,
        cursor: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncPager[RetrievalLogEntry]:
        """
        Per-conversation retrieval log, newest first — one row per
        `search_knowledge` invocation made during the call. Each entry
        records the query, ranked chunks (denormalised so deletions
        don't render history unreadable), `top_k`, and hit count.
        Powers the Retrieval panel on the conversation detail view.
        Cursor-paginated: omit `cursor` to fetch the first page.
        Default page size is 50 and max is 200. Walk pages while
        `has_more` is true.

        Parameters
        ----------
        id : str

        cursor : typing.Optional[str]
            Opaque pagination cursor from a previous response.

        limit : typing.Optional[int]
            Max retrieval log entries per page (default 50, max 200).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncPager[RetrievalLogEntry]
            The retrieval log entries for the conversation.

        Examples
        --------
        import asyncio

        from speechify import AsyncSpeechify

        client = AsyncSpeechify(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            response = await client.agent.conversations.list_retrieval_log(
                id="id",
            )
            async for item in response:
                yield item
            # alternatively, you can paginate page-by-page
            async for page in response.iter_pages():
                yield page


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/agents/conversations/{jsonable_encoder(id)}/retrieval-log",
            method="GET",
            params={
                "cursor": cursor,
                "limit": limit,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _parsed_response = typing.cast(
                    ListRetrievalLogsResponse,
                    parse_obj_as(
                        type_=ListRetrievalLogsResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                _parsed_next = _parsed_response.next_cursor
                _has_next = _parsed_next is not None and _parsed_next != ""
                _get_next = lambda: self.list_retrieval_log(
                    id,
                    cursor=_parsed_next,
                    limit=limit,
                    request_options=request_options,
                )
                _items = _parsed_response.entries
                return AsyncPager(has_next=_has_next, items=_items, get_next=_get_next)
            if _response.status_code == 400:
                raise BadRequestError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def list_memories(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ListMemoriesResponse:
        """
        List memories extracted from a specific conversation.

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListMemoriesResponse
            Memories written during this conversation.

        Examples
        --------
        import asyncio

        from speechify import AsyncSpeechify

        client = AsyncSpeechify(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.agent.conversations.list_memories(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/agents/conversations/{jsonable_encoder(id)}/memories",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    ListMemoriesResponse,
                    parse_obj_as(
                        type_=ListMemoriesResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)
